'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''

        

from datatypes import *
from utils import *



##### ABSTRACT SYNTAX TREE #####


        
### MODULE : MAIN ###


class PROGRAM(Rule):
   r'''```
<PROGRAM> ::= <GRAMMAR>
    ```'''

class GRAMMAR(Rule):
   r'''```
<GRAMMAR> ::= <LINE>
            | <LINE> \n+ <GRAMMAR>
    ```'''

class LINE(Rule):
   r'''```
<LINE> ::= <REQUIRE>
         | <PRODUCTION>
    ```'''

class REQUIRE(Rule):
   r'''```
<REQUIRE> ::= #require\s+\w+(\.\w+)*
    ```'''

class PRODUCTION(Rule):
   r'''```
<PRODUCTION> ::= <RULE> -> <ALTERNATIVES>
    ```'''

class RULE(Rule):
   r'''```
<RULE> ::= <NONTERMINAL>
    ```'''

class ALTERNATIVES(Rule):
   r'''```
<ALTERNATIVES> ::= <PATTERN>
                 | <PATTERN> / <ALTERNATIVES>
    ```'''

class PATTERN(Rule):
   r'''```
<PATTERN> ::= <TERM>
            | <TERM> <PATTERN>
    ```'''

class TERM(Rule):
   r'''```
<TERM> ::= <TERMINAL>
         | <NONTERMINAL>
    ```'''

class NONTERMINAL(Rule):
   r'''```
<NONTERMINAL> ::= [_a-zA-Z]\w*
    ```'''

class TERMINAL(Rule):
   r'''```
<TERMINAL> ::= "\S+"
    ```'''



##### GRAMMAR #####



_MODULES = {

'MAIN' : {
   PROGRAM       : [[GRAMMAR]],
   GRAMMAR       : [[LINE], [LINE, r'\n+', GRAMMAR]],
   LINE          : [[REQUIRE], [PRODUCTION]],
   REQUIRE       : [[r'#require\s+\w+(\.\w+)*']],
   PRODUCTION    : [[RULE, r'->', ALTERNATIVES]],
   RULE          : [[NONTERMINAL]],
   ALTERNATIVES  : [[PATTERN], [PATTERN, r'/', ALTERNATIVES]],
   PATTERN       : [[TERM], [TERM, PATTERN]],
   TERM          : [[TERMINAL], [NONTERMINAL]],
   NONTERMINAL   : [[r'[_a-zA-Z]\w*']],
   TERMINAL      : [[r'"\S+"']]
   }

}

_GRAMMAR = { START : { ProductionData(START, "MAIN", 0, [PROGRAM]) } }

for module, grammar in _MODULES.items():
    for rule, alternatives in grammar.items():
        if not rule in _GRAMMAR: _GRAMMAR[rule] = set()
        
        for variant, pattern in enumerate(alternatives):
            _GRAMMAR[rule].add(ProductionData(rule, module, variant, pattern))



##### ADDENDA #####



_TOKENS = {
    token 
            for options in _GRAMMAR.values()
        for metadata in options
    for token in metadata.pattern
}

_TERMINALS = set(filter(lambda x: isinstance(x, str), _TOKENS))
