from parser.AST import *

from rich import print
from rich.table import Table

from importlib import reload



class LALR1:
    """LALR(1) Parser."""

    def __init__(self, debug: bool = False):
        self.rules = list(e for opts in GRAMMAR.values() for e in opts)
        self.nulls: set = set()
        self.automaton: dict[int, dict[Item, set]] = {}
        self.table: dict[int, dict[str|ProductionData, int]] = {}
        self.kernels: dict[Item, int] = {}
        self.first: dict[Rule] = {}
        self.conflicts = ""

        self.debug = debug
    
    
    def cache(self) -> 'LALR1':
        import parser.parsetable as parsetable
        reload(parsetable)
        self.rules = parsetable.RULES
        self.table = parsetable.TABLE
        return self


    def generate(self):
        
        self.construct_automaton(self.closure({
            Item(0, ProductionData(START, "MAIN", 0, [ PROGRAM ])) : { EOI }
            }))
        self.construct_table()
        
        if self.debug:

            print()

            print("GRAMMAR")
            print(GRAMMAR)
            
            print()

            print("AUTOMATON")
            print(self.automaton)
            
            print()
            
            self.show_tables()

        with open(f"{get_config("paths", "generated")}/parsetable.py", "w") as file:
            file.write(self.tableToStr())


    def tableToStr(self) -> str:
        def norm(x): return (
            f"r'{x}'" if isinstance(x, str) 
            else x.__repr__() if isinstance(x, ProductionData)
            else x if isinstance(x, (int, float, bool, type(None))) 
            else x.__name__
        )

        return f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from parser.AST import *



# ---{{ GRAMMAR }}---
{"\n".join(f"# Rule {i:<4} {str(rule)}" for i, rule in enumerate(self.rules))}



# Parsetable constructed with {len(self.table)} state{"s"*(len(self.table)!=1)}.
# {self.conflicts.replace("\n", "\n# ")}



RULES = (
    {",\n    ".join(f"{norm(rule)}" for rule in self.rules)}
)



TABLE = {{ 
    {",\n    ".join(f"""{state} : {{
        {",\n        ".join(f"{norm(token)} : {actions}" for token, actions in transitions.items())}
    }}""" for state, transitions in self.table.items())}
}}
"""
        

    def isNullable(self, rule: Rule|str) -> bool:
        return (
            (not isinstance(rule, str))
            and any(
                    (productionData.isNull or all(self.isNullable(token) for token in productionData.pattern if not (token == rule)))
                    for productionData in GRAMMAR[rule]
                )
            )


    def construct_automaton(self, closure: dict[Item, set]) -> None:
        """Constructs the LALR automaton."""

        def merge(existingState: dict[Item, set], newState: dict[Item, set]) -> bool:
            if (existingState.keys() == newState.keys()):
                for item, lookahead in newState.items():
                    existingState[item].update(lookahead)
                return True
            return False
            
        state = len(self.automaton)
        self.automaton[state] = closure

        for items in self.get_transitions(self.automaton[state]).values():

            nextKernel = {
                Item(item.dot+1, item.production) : lookahead
                for item, lookahead in items.items()
            }

            nextClosure = self.closure(nextKernel)
            for closure in self.automaton.values():
                if merge(closure, nextClosure): break
            else: 
                self.construct_automaton(nextClosure)


    def get_transitions(self, state: dict[Item, set]) -> dict[str|Rule, dict[Item, set]]:
        "Organize transitions out of a given state closure by token."

        transitions = {}

        for item, lookahead in state.items():
            if item.isReduction: continue

            if not item.current in transitions: transitions[item.current] = {}

            transitions[item.current][item] = lookahead

        return transitions


    def construct_table(self) -> None:
        """Constructs the LALR table."""

        conflicts = {}

        for state, closure in self.automaton.items():
            self.table[state] = {}

            transitions = self.get_transitions(closure)
            reductions = { item : lookahead for item, lookahead in closure.items() if item.isReduction }

            for item, lookahead in reductions.items():
                for token in lookahead:
                    self.table[state][token] = self.table[state].get(token, set()).union({
                        ("A", True) if (item.production.rule, token) == (START, EOI)
                        else ("R", self.rules.index(item.production))
                    })

            for token, kernel in transitions.items():
                nextItems = {
                        Item(item.dot+1, item.production)
                        for item in kernel
                    }
                action = ("S" if isinstance(token, str) else "G")
                
                self.table[state][token] = self.table[state].get(token, set()).union({ 
                        (action, toState) for toState, toClosure in self.automaton.items() if nextItems.issubset(toClosure)
                    })

            for token, actions in self.table[state].items():
                self.table[state][token] = list(sorted(actions, key=lambda tup: tup[0] == "R"))
                
                if len(actions) > 1:
    
                    if not state in conflicts:
                        conflicts[state] = {}

                    conflict = "/".join(action[0] for action in self.table[state][token])

                    if not conflict in conflicts:
                        conflicts[state][conflict] = []
                    
                    conflicts[state][conflict].append(token)

        if conflicts: 
            self.conflicts = f"Found {len(conflicts)} conflicts."
            for state, conflictTypes in conflicts.items():
                for label, tokens in conflictTypes.items():
                    self.conflicts += f"\n(state {state}) {label} conflict on token{"s"*(len(tokens) != 1)} {", ".join(f"'{token}'" if isinstance(token, str) else token.__name__ for token in tokens)}"
        else:
            self.conflicts = "No conflicts found."

        print()
        print(self.conflicts)
        print()       


    def closure(self, kernel: dict[Item, set]) -> dict[Item, set]:
        """Computes the closure of a given configuration."""

        items: list[tuple[Item, set]] = []

        expansions = list(kernel.items())

        while expansions:

            # add the most recent rule to the expansion
            item, lookahead = expansions.pop()

            if (item, lookahead) in items: continue

            items.append((item, lookahead))

            # if the current token is a nonterminal, we must add further expansions
            if not (item.isReduction or isinstance(item.current, str)):
                
                newLookahead = self.FIRST(item.next, lookahead)

                for productionData in GRAMMAR[item.current]:
                    expansions.append((Item(0, productionData), newLookahead))

        out: dict[Item, set] = {}

        for (item, lookahead) in items:
            if item in out:
                out[item].update(lookahead)
            else:
                out[item] = lookahead

        return out


    def FIRST(self, sequence: list[Rule|str], lookahead: set = None, exclude: set = None) -> set[str]:
    
        exclude = exclude or set()
        first = set()

        for token in sequence:
            if isinstance(token, str):
                first.add(token)
                break

            elif not token in exclude:
                for productionData in GRAMMAR[token]: 
                    first.update(self.FIRST(productionData.pattern, set(), exclude.union({token})))
                
                if self.isNullable(token): continue
                else: break

        else: first.update(lookahead)

        return first

            
    def parse(self, input: list[Token], symbols: list = None, state: list = None) -> Rule:
        if symbols is None: symbols = []
        if state is None: state = [0]

        if self.debug:

            parserOutput = table(
                title="Parser Output",
                headers={
                    "Step" : {"justify" : "center"},
                    "State" : {},
                    "Symbols" : {},
                    "Input" : {"justify" : "right"},
                    "Action" : {"justify" : "center"}
                }
            )
        
        step = -1
        try:
            while input:
                step += 1
                
                action, data = self.table[state[-1]].get(input[0].regex, [("E", False)])[0]
                
                if self.debug:
                    parserOutput.add_row(
                        str(step), 
                        " ".join(tostr(state)), 
                        " ".join(tostr(symbols)), 
                        " ".join(tostr(input)), 
                        { "A" : "ACC", "E" : "ERR" }.get(action, f"{action} {data}")
                    )
    
                match action:
                    
                    case "S":
                        symbols.append(input.pop(0))
                        state.append(data)

                    case "R":
                        production: ProductionData = self.rules[data]
                        reduction = []

                        for _ in production.pattern:
                            reduction.append(symbols.pop())
                            state.pop()
                        
                        symbols.append(production.rule(reversed(reduction), production.module, production.variant))
                        
                        # Handle goto as part of reduce action
                        action, data = self.table[state[-1]][production.rule][0]
                        if action == "G": state.append(data)
                        else: raise ParseError(f"expected goto on token {state[-1]}")

                    case "A":
                        if len(symbols) == 1 and isinstance(symbols[0], PROGRAM): break
                        raise ParseError("could not parse expression")
                    
                    case "E": 
                        expected = set(tok for tok in self.table[state[-1]].keys() if isinstance(tok, str))
                        
                        raise ParseError(f"""unexpected {
                            f"{input[0].info} (Token matched r'{input[0].regex}')" if isinstance(input[0], Token) 
                            else f" {input[0]}"
                        }
    expected {", ".join(expected)}""")
                    
                    case _: raise ParseError(f"unknown action {action} in state {state}")
        
        finally:
            if self.debug: print(parserOutput, "")

        return symbols.pop()

    
    def show_tables(self) -> None:

        categories = list(sorted(TERMINALS)) + [EOI] + list(rule for rule in GRAMMAR.keys() if not rule == START)

        self.display_table = Table(title="LALR(1) Parsing Table")
        self.display_table.add_column("State", justify="center")
        for category in categories:
            self.display_table.add_column(category if isinstance(category, str) else category.__name__, justify="center")
        for state, edges in self.table.items():
            self.display_table.add_row(str(state), *(" ".join(map(str, edges.get(edge, ("",)))) for edge in categories))

        self.display_rules = Table.grid()
        self.display_rules.title = "Rules"
        self.display_rules.add_column(style="bright_cyan")
        for i, production in enumerate(self.rules):
            rule, pattern = str(production).split("::=")
            self.display_rules.add_row(f"{i} ", rule, "::=", pattern)

        print()
        print(self.display_table)
        print()
        print(self.display_rules)
        print()
