from datatypes import OrderedSet
from utils import *

import os
import re



class Eval:
    WARNINGS = {
        "dependency" : [],
        "main"       : []
    }
    LITERAL = True


    def __init__(self, dependencies: OrderedSet):
        self.dependencies = dependencies
        self.exception = """
    except Exception as e:
        raise e
"""

      
    def compile(self) -> str:
        text = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, Token
from utils import *

from collections.abc import Sequence



##### MODULES #####
""" \
        + "".join(File(dependency).compile() for dependency in self.dependencies) \
        + File().compile() \
        + f"""

        
##### EVAL #####



class Expr(Sequence):
    '''Immutable, callable `Sequence` object which returns its elements as instances of itself.'''

    ATTRIBUTES = {{ fname : func for fname, func in globals().items() if fname.startswith("p_")}}

    def __new__(cls, node):
        return (
            super().__new__(cls) if isinstance(node, Rule)
            else node.tok if isinstance(node, Token)
            else node
        )
        
    def __init__(self, node: Rule):
        self._children = node.children
        self._node = node

    def __getitem__(self, index: int|slice):
        item = self._children[index]
        if isinstance(index, slice):
            return tuple(Expr(e) for e in item)
        return Expr(item)
  
    def __len__(self):
        return len(self._children)
   
    def __str__(self):
        return self._node.__str__()

    def __repr__(self):
        return self._node.__repr__()

    def __call__(self, i: int = None, *args, **kwargs):
        e = self if (i == None) else self[i]
        return _evaluate(e, *args, **kwargs)

{self.embed_default()}

def _get_function(node: Rule):
    return (
        Expr.ATTRIBUTES.get(f"{{node.fname}}_{{node.variant}}")
        or Expr.ATTRIBUTES.get(node.fname)
        or _default
    )


def _evaluate(expr, *args, **kwargs):
    return (
        _get_function(expr._node)(expr, *args, **kwargs) if isinstance(expr, Expr)
        else expr
    )


def parse(expr: str):
    from parser.lalr import LALR1
    return Expr(LALR1().cache().parse(expr))
"""
        
        print_warnings("semantics not found", self.WARNINGS)
        
        return text
    

    def embed_default(self) -> str:

        if (get_config("implementation") == "interpreter"):
            return """
def _default(x: Expr): return x(0)
"""

        else: 
            return """
def _default(x: Expr): return " ".join((e() if isinstance(e, Expr) else str(e)) for e in x)
"""



class File:
    def __init__(self, path: str = None):
        """Resolve and compile syntax files. 
        Search for semantics.py in `path/<implementation>/`;
        if not found, fall back to `path/`."""

        main = get_config("paths", "language")

        if path: 
            self.type = "DEPENDENCY"
            self.path = path
        else:
            self.type = "MAIN"
            self.path = main

        implementation = get_config("implementation")
        self.file = f"{self.path}/{implementation}/semantics.py"
        if not os.path.exists(self.file):
            self.file = f"{self.path}/semantics.py"

            if (self.type == "MAIN") and os.path.exists(self.file): 
                print_warnings(
                    msg=f"using default semantics",
                    log={"may not be implementation-specific" : [self.path]}
                )


    def compile(self) -> str:
        if not os.path.exists(self.file):
            Eval.WARNINGS[self.type.lower()].append(self.path)
            return ""
    
        with open(self.file) as file:
            Eval.LITERAL = False
            text = self.process(file.read())
            return f"""


### {self.type} : {self.path} ###



""" + text
        

    def process(self, text: str) -> str:

        def replace_fname(match: re.Match) -> str:
            return (
                pathToFunc(self.path if self.type == "DEPENDENCY" else "main")
                + match.group().split("p_", 1)[1].lower()
            )

        return re.sub(
            pattern=r"p_.*\(",
            repl=replace_fname,
            string=text
        )
