'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import *

from collections.abc import Sequence



##### main #####



from utils import *

import os



g_newlines = False
g_indentation = False
g_module: dict = "main"
g_paths: list = ["main"]
g_grammar: dict[Nonterminal, list[Production]] = {
    START() : [ Production(START(), "main", 0, [Nonterminal("PROGRAM")]) ]
}
g_terminals: set = set()
g_conflicts: str = ""
g_warnings: dict = {
    "syntax" : {},
    "semantics" : {}
}
g_eval: str = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import *

from collections.abc import Sequence



"""



##### eval functions #####



def p_main_program(expr, module: str = "main"):
    
    from compiler import parse
    
    global g_module
    global g_paths
    global g_grammar
    global g_terminals
    global g_conflicts
    global g_warnings
    global g_eval


    def get_filename(directory: str, file: str):
        """Tries to find a syntax/semantics file in the given directory."""
        
        filename = f"{directory}/{CONFIG.implementation}/{file}"
        
        if not os.path.exists(filename):
            filename = f"{directory}/{file}"
        
        if not os.path.exists(filename):
            filename = None

            category = file.split(".")[0]
            subcategory = ("main" if module == "main" else "dependency")
            if subcategory not in g_warnings[category]: g_warnings[category][subcategory] = []
            g_warnings[category][subcategory].append(directory)
        
        return filename
        

    g_module = module
    expr(0)
    g_module = module

    if module == "main":
        print("Metacompiling") if CONFIG.flags.metacompile else print(f"Compiling" + (" onefile" if CONFIG.flags.onefile else ""))
        print()
    else: return

    for path in g_paths:

        directory = CONFIG.paths.language if (path == "main") else os.path.join(CONFIG.paths.lib, path)
        modulename = path.replace("/", "_")

        if not path == "main":

            # read syntax; syntax for main module handled by default
            filename = get_filename(directory, "syntax.txt")
            if filename is not None:
                with open(filename) as file:
                    Expr(parse(file.read()))(None, modulename)
            
        # read semantics
        filename = get_filename(directory, "semantics.py")
        
        if (filename is None) and (path == "main"): CONFIG.implementation = "compiler"
        
        if filename is not None:
            g_eval += f"""##### {path} #####



{embed_eval(filename, modulename)}


"""
            
    AST = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, EOI



##### ABSTRACT SYNTAX TREE #####


"""

    for category, warnings in g_warnings.items(): 
        print_warnings(f"{category} not found", warnings)

    for rule, alternatives in g_grammar.items():
        AST += f"""
class {rule}(Rule):
    r'''```
{rule} -> {("\n"+" "*(len(rule)+2)+"| ").join(
    (lstToStr(production.pattern) if production.pattern else "\"\"")
    for production in alternatives
    )}
    ```'''
"""
    
    AST += f"""

terminals = {{
    {",\n    ".join((token.__repr__() for token in g_terminals))}
}}


{get_parsetable_str()}
"""
    
    g_eval += f"""##### evaluation #####



class Expr(Sequence):
    \"""Immutable, callable `Sequence` object which returns its elements as instances of itself.\"""

    SEMANTICS = {{ fname : func for fname, func in globals().items() if fname.startswith("p_")}}

    def __new__(cls, node):
        return (
            super().__new__(cls) if isinstance(node, Rule)
            else node.tok if isinstance(node, Token)
            else node
        )
        
    def __init__(self, node: Rule):
        self._children = node.children
        self._node = node

    def __getitem__(self, index: int|slice):
        item = self._children[index]
        if isinstance(index, slice):
            return tuple(Expr(e) for e in item)
        return Expr(item)
  
    def __len__(self):
        return len(self._children)
   
    def __str__(self):
        return self._node.__str__()

    def __repr__(self):
        return self._node.__repr__()

    def __call__(self, i: int = None, *args, **kwargs):
        e = self if (i == None) else self[i]
        return _evaluate(e, *args, **kwargs)


def _default(x: Expr):
    return {"x(0)" if (CONFIG.implementation == "interpreter") else "\"\".join(x(i) for i in range(len(x)))"}


def _get_function(node: Rule):
    return (
        Expr.SEMANTICS.get(f"{{node.fname}}_{{node.variant}}")
        or Expr.SEMANTICS.get(node.fname)
        or _default
    )


def _evaluate(expr, *args, **kwargs):
    return (
        _get_function(expr._node)(expr, *args, **kwargs) if isinstance(expr, Expr)
        else expr
    )
"""

    if CONFIG.flags.metacompile:
        with open(os.path.join(CONFIG.paths.root, "compiler/parserdata.py"), "w") as file:
            file.write(AST)
        with open(os.path.join(CONFIG.paths.root, "compiler/evaluation.py"), "w") as file:
            file.write(g_eval.strip() + "\n")
    else:
        with open(os.path.join(CONFIG.paths.root, "parser/parserdata.py"), "w") as file:
            file.write(AST)
        with open(os.path.join(CONFIG.paths.root, "parser/evaluation.py"), "w") as file:
            file.write(g_eval.strip() + "\n")


def p_main_grammar_1(expr):
    expr(0)
    expr(2)


def p_main_require(expr):
    global g_paths

    path = expr(0).removeprefix("#require").strip().split(".")
    paths = list("/".join(path[:i+1]) for i in range(len(path)))
    for path in paths:
        if not path in g_paths:
            g_paths.append(path)


def p_main_production(expr):
    global g_grammar
    global g_module

    rule, alternatives = expr(0), expr(2)
    if not rule in g_grammar: g_grammar[rule] = []
    for variant, pattern in enumerate(alternatives):
        g_grammar[rule].append(Production(rule, g_module, variant, pattern))


def p_main_alternatives_0(expr):
    return [list(expr(0))]

def p_main_alternatives_1(expr):
    return [list(expr(0))] + expr(2)


def p_main_pattern_0(expr):
    return (expr(0), )

def p_main_pattern_1(expr):
    return (expr(0), *expr(1))


def p_main_nonterminal(expr):
    global g_indentation

    nonterminal = Nonterminal(expr(0))
    g_indentation = g_indentation or (nonterminal.rule in ("INDENT", "DEDENT"))
    
    return nonterminal


def p_main_terminal_0(expr):
    global g_newlines
    
    terminal = Terminal(expr(0)[1:-1])
    g_newlines = g_newlines or (r"\n" in terminal.regex)
    
    g_terminals.add(terminal)

    return terminal


def p_main_terminal_1(expr):
    return EPSILON()



##### parsing #####



def get_parsetable_str():
    global g_grammar


    rules = list(e for opts in g_grammar.values() for e in opts)

    COLLECTION: list[set[Item]] = []
    GOTO: dict[int, dict[Terminal|Nonterminal, int]] = {}
    LA: dict[int, dict[Item, set[Terminal]]] = {}
    AUTOMATON: list[set[Item]] = []
    TABLE: dict[int, dict[Terminal|Nonterminal, list[tuple[str, int]]]] = {}
    

    def CANONICAL(itemset: set[Item]) -> dict:
        """Compute the canonical LR(0) collection."""

        state = len(COLLECTION)
        COLLECTION.append(itemset)
        for token, itemset in GOTOS(COLLECTION[-1]):
            if itemset in COLLECTION:
                GOTO[state][token] = COLLECTION.index(itemset)
            else:
                GOTO[state][token] = len(COLLECTION)
                CANONICAL(itemset)


    def CLOSURE(kernel: set[Item]) -> set[Item]:
        """Compute the closure of an LR(0) kernel."""

        closure = set()
        expansions = kernel
        while expansions:
            item = expansions.pop()
            if item in closure: continue
            closure.add(item)
            if isinstance(item.current, Nonterminal):
                for production in g_grammar[item.current]:
                    expansions.add(Item(0, production))
        return closure
    

    def GOTOS(itemset: set[Item]) -> dict[Terminal|Nonterminal, set[Item]]:
        """Compute the goto transitions of a given state."""

        gotos: dict[Terminal|Nonterminal, set[Item]] = {}
        for item in itemset:
            if item.isReduction: continue
            if item.current not in gotos: gotos[item.current] = set()
            gotos[item.current].add(Item(item.dot+1, item.production))
        for token, kernel in gotos.items():
            gotos[token] = CLOSURE(kernel)
        return gotos


    CANONICAL(CLOSURE(
        { Item(0, Production(START(), "MAIN", 0, [Nonterminal("PROGRAM")])) }
    ))

    
    def DIGRAPH() -> None:
        pass
    

    def LOOKAHEADS() -> None:
        """Propagate lookaheads across the LALR(1) automaton based on the DeRemer-Penello method."""
        
        for state, itemset in enumerate(COLLECTION):
            LA[state] = {}
            for item in itemset:
                LA[state][item] = {}

        

        spontaneous: list[dict[Item, set[Terminal]]] = []
        # spontaneous: list[dict[Item, set[Terminal]]] = [{ item : {EOI()} for item in COLLECTION[0]}]
        
        for state, itemset in enumerate(COLLECTION):
            spontaneous.append({})
            for item in itemset:
                spontaneous[state][item] = {EOI()} if (state == 0) else FIRST(item.next)
                


    def FIRST(sequence: list[Terminal|Nonterminal], lookahead: set[Terminal] = None, exclude: set[Nonterminal] = None) -> set[Terminal]:
        if exclude is None: exclude = set()
        first: set[Terminal|Nonterminal] = set()
        for token in sequence:
            if isinstance(token, Terminal):
                return first.union({token})
            if token not in exclude:
                for production in g_grammar[token]:
                    first.update(FIRST(production.pattern, exclude=exclude.union({token})))
                if not NULLABLE(token): return first
        return first.union(lookahead)


    def NULLABLE(rule: Terminal|Nonterminal) -> bool:
        return (
            isinstance(rule, Nonterminal)
            and any(
                (production.pattern == [])
                or all(NULLABLE(token) for token in production.pattern if not token == rule)
                for production in g_grammar[rule]
            )
        )
    

        if conflicts: 
            g_conflicts = f"Found {len(conflicts)} conflicts."
            for state, conflictTypes in conflicts.items():
                for label, tokens in conflictTypes.items():
                    g_conflicts += f"\n(state {state}) {label} conflict on token{"s"*(len(tokens) != 1)} {", ".join(token.__repr__() for token in tokens)}"
        else:
            g_conflicts = "No conflicts found."
    


    construct_automaton(construct_closure({
        Item(0, Production(START(), "MAIN", 0, [Nonterminal("PROGRAM")])) : { EOI() } 
        }))
    construct_table()

    
    
    grammar = f"""-------{{ GRAMMAR }}-------
{"\n".join(f"Rule {i:<3} {str(rule)}" for i, rule in enumerate(rules))}"""

    if CONFIG.flags.debug: 
        print(grammar)
        print()

        categories = [*sorted(g_terminals, key=str), EOI(), *g_grammar.keys()]
        categories.remove(START())
        parsetable = displayTable(
            title="LALR Table",
            columns=dict.fromkeys(("State", *map(str, categories)), {}),
            rows=[(str(state), *(lstToStr(edges.get(token, [("",)])[0]) for token in categories)) for state, edges in table.items()]
            )
        
        print("------{ AUTOMATON }------")
        for state, closure in automaton.items():
            print(f"State {state}")
            for item, lookahead in closure.items():
                print(f"    {item}, {"/".join(map(str, lookahead))}")
        print()

        print(parsetable)


    return f"""
##### PARSETABLE #####



# {str(grammar).replace("\n", "\n# ")}



# Parsetable constructed with {len(table)} state{"s"*(len(table)!=1)}.
# {g_conflicts.replace("\n", "\n# ")}



indentation = {g_indentation}
newlines = {g_newlines}



rules = (
    {",\n    ".join(rule.__repr__() for rule in rules)}
)



table = {{
    {",\n    ".join(f"""{state} : {{
        {",\n        ".join(f"{token.__repr__()} : {actions}" for token, actions in transitions.items())}
    }}""" for state, transitions in table.items())}
}}"""


def embed_eval(filename: str, modulename: str) -> str:
    from re import Match
    from re import sub

    def replace_fname(match: Match) -> str:
        return f"p_{modulename}_{match.group().removeprefix("p_")}"

    with open(filename) as file:
        return sub(
            pattern=r"p_\w*\(",
            repl=replace_fname,
            string=file.read()
        )



##### evaluation #####



class Expr(Sequence):
    """Immutable, callable `Sequence` object which returns its elements as instances of itself."""

    SEMANTICS = { fname : func for fname, func in globals().items() if fname.startswith("p_")}

    def __new__(cls, node):
        return (
            super().__new__(cls) if isinstance(node, Rule)
            else node.tok if isinstance(node, Token)
            else node
        )
        
    def __init__(self, node: Rule):
        self._children = node.children
        self._node = node

    def __getitem__(self, index: int|slice):
        item = self._children[index]
        if isinstance(index, slice):
            return tuple(Expr(e) for e in item)
        return Expr(item)
  
    def __len__(self):
        return len(self._children)
   
    def __str__(self):
        return self._node.__str__()

    def __repr__(self):
        return self._node.__repr__()

    def __call__(self, i: int = None, *args, **kwargs):
        e = self if (i == None) else self[i]
        return _evaluate(e, *args, **kwargs)


def _default(x: Expr):
    return x(0)


def _get_function(node: Rule):
    return (
        Expr.SEMANTICS.get(f"{node.fname}_{node.variant}")
        or Expr.SEMANTICS.get(node.fname)
        or _default
    )


def _evaluate(expr, *args, **kwargs):
    return (
        _get_function(expr._node)(expr, *args, **kwargs) if isinstance(expr, Expr)
        else expr
    )
