'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, EOI



##### ABSTRACT SYNTAX TREE #####



class START(Rule):
    r'''```
START -> PROGRAM $
    ```'''

class PROGRAM(Rule):
    r'''```
PROGRAM -> GRAMMAR
    ```'''

class GRAMMAR(Rule):
    r'''```
GRAMMAR -> LINE
         | LINE "\n+" GRAMMAR
    ```'''

class LINE(Rule):
    r'''```
LINE -> REQUIRE
      | PRODUCTION
    ```'''

class REQUIRE(Rule):
    r'''```
REQUIRE -> "#require" NAME
         | "#require" NAME "as" NAME
    ```'''

class NAME(Rule):
    r'''```
NAME -> "\w+(\.\w+)*"
    ```'''

class PRODUCTION(Rule):
    r'''```
PRODUCTION -> RULE "->" ALTERNATIVES
    ```'''

class RULE(Rule):
    r'''```
RULE -> NONTERMINAL
    ```'''

class ALTERNATIVES(Rule):
    r'''```
ALTERNATIVES -> PATTERN
              | PATTERN "\|" ALTERNATIVES
    ```'''

class PATTERN(Rule):
    r'''```
PATTERN -> TERM
         | TERM PATTERN
    ```'''

class TERM(Rule):
    r'''```
TERM -> TERMINAL
      | NONTERMINAL
    ```'''

class NONTERMINAL(Rule):
    r'''```
NONTERMINAL -> "\w+(\.\w+)*"
    ```'''

class TERMINAL(Rule):
    r'''```
TERMINAL -> "\"\S+\""
          | "\"\""
    ```'''



##### PARSETABLE #####



# --------{ GRAMMAR }--------
# Rule 0   START -> PROGRAM $
# Rule 1   PROGRAM -> GRAMMAR
# Rule 2   GRAMMAR -> LINE
# Rule 3   GRAMMAR -> LINE "\n+" GRAMMAR
# Rule 4   LINE -> REQUIRE
# Rule 5   LINE -> PRODUCTION
# Rule 6   REQUIRE -> "#require" NAME
# Rule 7   REQUIRE -> "#require" NAME "as" NAME
# Rule 8   NAME -> "\w+(\.\w+)*"
# Rule 9   PRODUCTION -> RULE "->" ALTERNATIVES
# Rule 10  RULE -> NONTERMINAL
# Rule 11  ALTERNATIVES -> PATTERN
# Rule 12  ALTERNATIVES -> PATTERN "\|" ALTERNATIVES
# Rule 13  PATTERN -> TERM
# Rule 14  PATTERN -> TERM PATTERN
# Rule 15  TERM -> TERMINAL
# Rule 16  TERM -> NONTERMINAL
# Rule 17  NONTERMINAL -> "\w+(\.\w+)*"
# Rule 18  TERMINAL -> "\"\S+\""
# Rule 19  TERMINAL -> "\"\""



# Parsetable constructed with 28 states.
# No conflicts found.



indentation = False
newlines = True



rules = (
    (START, 'main', 0, 2),
    (PROGRAM, 'main', 0, 1),
    (GRAMMAR, 'main', 0, 1),
    (GRAMMAR, 'main', 1, 3),
    (LINE, 'main', 0, 1),
    (LINE, 'main', 1, 1),
    (REQUIRE, 'main', 0, 2),
    (REQUIRE, 'main', 1, 4),
    (NAME, 'main', 0, 1),
    (PRODUCTION, 'main', 0, 3),
    (RULE, 'main', 0, 1),
    (ALTERNATIVES, 'main', 0, 1),
    (ALTERNATIVES, 'main', 1, 3),
    (PATTERN, 'main', 0, 1),
    (PATTERN, 'main', 1, 2),
    (TERM, 'main', 0, 1),
    (TERM, 'main', 1, 1),
    (NONTERMINAL, 'main', 0, 1),
    (TERMINAL, 'main', 0, 1),
    (TERMINAL, 'main', 1, 1)
)



table = {
    0 : {
        PRODUCTION : [('G', 1)],
        r"#require" : [('S', 2)],
        PROGRAM : [('G', 7)],
        r"\w+(\.\w+)*" : [('S', 9)],
        LINE : [('G', 10)],
        REQUIRE : [('G', 13)],
        NONTERMINAL : [('G', 14)],
        RULE : [('G', 15)],
        GRAMMAR : [('G', 27)]
    },
    1 : {
        r"\n+" : [('R', 5)],
        EOI : [('R', 5)]
    },
    2 : {
        r"\w+(\.\w+)*" : [('S', 3)],
        NAME : [('G', 4)]
    },
    3 : {
        r"\n+" : [('R', 8)],
        r"as" : [('R', 8)],
        EOI : [('R', 8)]
    },
    4 : {
        r"\n+" : [('R', 6)],
        EOI : [('R', 6)],
        r"as" : [('S', 5)]
    },
    5 : {
        r"\w+(\.\w+)*" : [('S', 3)],
        NAME : [('G', 6)]
    },
    6 : {
        r"\n+" : [('R', 7)],
        EOI : [('R', 7)]
    },
    7 : {
        EOI : [('S', 8)]
    },
    8 : {
        None : [('A', True)]
    },
    9 : {
        r"\|" : [('R', 17)],
        r"\"\"" : [('R', 17)],
        EOI : [('R', 17)],
        r"->" : [('R', 17)],
        r"\w+(\.\w+)*" : [('R', 17)],
        r"\n+" : [('R', 17)],
        r"\"\S+\"" : [('R', 17)]
    },
    10 : {
        EOI : [('R', 2)],
        r"\n+" : [('S', 11)]
    },
    11 : {
        PRODUCTION : [('G', 1)],
        GRAMMAR : [('G', 12)],
        r"#require" : [('S', 2)],
        r"\w+(\.\w+)*" : [('S', 9)],
        LINE : [('G', 10)],
        REQUIRE : [('G', 13)],
        NONTERMINAL : [('G', 14)],
        RULE : [('G', 15)]
    },
    12 : {
        EOI : [('R', 3)]
    },
    13 : {
        r"\n+" : [('R', 4)],
        EOI : [('R', 4)]
    },
    14 : {
        r"->" : [('R', 10)]
    },
    15 : {
        r"->" : [('S', 16)]
    },
    16 : {
        PATTERN : [('G', 17)],
        TERM : [('G', 20)],
        TERMINAL : [('G', 22)],
        NONTERMINAL : [('G', 23)],
        ALTERNATIVES : [('G', 26)],
        r"\"\"" : [('S', 19)],
        r"\"\S+\"" : [('S', 24)],
        r"\w+(\.\w+)*" : [('S', 9)]
    },
    17 : {
        r"\n+" : [('R', 11)],
        EOI : [('R', 11)],
        r"\|" : [('S', 18)]
    },
    18 : {
        r"\"\"" : [('S', 19)],
        PATTERN : [('G', 17)],
        TERM : [('G', 20)],
        TERMINAL : [('G', 22)],
        NONTERMINAL : [('G', 23)],
        ALTERNATIVES : [('G', 25)],
        r"\"\S+\"" : [('S', 24)],
        r"\w+(\.\w+)*" : [('S', 9)]
    },
    19 : {
        r"\|" : [('R', 19)],
        r"\"\"" : [('R', 19)],
        EOI : [('R', 19)],
        r"\w+(\.\w+)*" : [('R', 19)],
        r"\n+" : [('R', 19)],
        r"\"\S+\"" : [('R', 19)]
    },
    20 : {
        PATTERN : [('G', 21)],
        TERM : [('G', 20)],
        TERMINAL : [('G', 22)],
        NONTERMINAL : [('G', 23)],
        r"\"\"" : [('S', 19)],
        r"\"\S+\"" : [('S', 24)],
        r"\|" : [('R', 13)],
        r"\n+" : [('R', 13)],
        EOI : [('R', 13)],
        r"\w+(\.\w+)*" : [('S', 9)]
    },
    21 : {
        r"\|" : [('R', 14)],
        r"\n+" : [('R', 14)],
        EOI : [('R', 14)]
    },
    22 : {
        r"\|" : [('R', 15)],
        r"\"\"" : [('R', 15)],
        EOI : [('R', 15)],
        r"\w+(\.\w+)*" : [('R', 15)],
        r"\n+" : [('R', 15)],
        r"\"\S+\"" : [('R', 15)]
    },
    23 : {
        r"\|" : [('R', 16)],
        r"\"\"" : [('R', 16)],
        EOI : [('R', 16)],
        r"\w+(\.\w+)*" : [('R', 16)],
        r"\n+" : [('R', 16)],
        r"\"\S+\"" : [('R', 16)]
    },
    24 : {
        r"\|" : [('R', 18)],
        r"\"\"" : [('R', 18)],
        EOI : [('R', 18)],
        r"\w+(\.\w+)*" : [('R', 18)],
        r"\n+" : [('R', 18)],
        r"\"\S+\"" : [('R', 18)]
    },
    25 : {
        r"\n+" : [('R', 12)],
        EOI : [('R', 12)]
    },
    26 : {
        r"\n+" : [('R', 9)],
        EOI : [('R', 9)]
    },
    27 : {
        EOI : [('R', 1)]
    }
}