'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, EOI



##### AST #####



class START(Rule):None
class PROGRAM(Rule):None
class GRAMMAR(Rule):None
class LINE(Rule):None
class REQUIRE(Rule):None
class NAME(Rule):None
class PRODUCTION(Rule):None
class RULE(Rule):None
class ALTERNATIVES(Rule):None
class PATTERN(Rule):None
class TERM(Rule):None
class NONTERMINAL(Rule):None
class TERMINAL(Rule):None



##### PARSETABLE #####



# --------{ GRAMMAR }--------
# Rule 0   START -> PROGRAM $
# Rule 1   PROGRAM -> GRAMMAR
# Rule 2   GRAMMAR -> LINE
# Rule 3   GRAMMAR -> LINE "\n+" GRAMMAR
# Rule 4   LINE -> REQUIRE
# Rule 5   LINE -> PRODUCTION
# Rule 6   REQUIRE -> "#require" NAME
# Rule 7   REQUIRE -> "#require" NAME "as" NAME
# Rule 8   NAME -> "\w+(\.\w+)*"
# Rule 9   PRODUCTION -> RULE "->" ALTERNATIVES
# Rule 10  RULE -> NONTERMINAL
# Rule 11  ALTERNATIVES -> PATTERN
# Rule 12  ALTERNATIVES -> PATTERN "\|" ALTERNATIVES
# Rule 13  PATTERN -> TERM
# Rule 14  PATTERN -> TERM PATTERN
# Rule 15  TERM -> TERMINAL
# Rule 16  TERM -> NONTERMINAL
# Rule 17  NONTERMINAL -> "\w+(\.\w+)*"
# Rule 18  TERMINAL -> "\"\S+\""
# Rule 19  TERMINAL -> "\"\""



# Parsetable constructed with 28 states.
# No conflicts found.



indentation = False
newlines = True



rules = (
    (START, 'MAIN', 0, 2),
    (PROGRAM, 'MAIN', 0, 1),
    (GRAMMAR, 'MAIN', 0, 1),
    (GRAMMAR, 'MAIN', 1, 3),
    (LINE, 'MAIN', 0, 1),
    (LINE, 'MAIN', 1, 1),
    (REQUIRE, 'MAIN', 0, 2),
    (REQUIRE, 'MAIN', 1, 4),
    (NAME, 'MAIN', 0, 1),
    (PRODUCTION, 'MAIN', 0, 3),
    (RULE, 'MAIN', 0, 1),
    (ALTERNATIVES, 'MAIN', 0, 1),
    (ALTERNATIVES, 'MAIN', 1, 3),
    (PATTERN, 'MAIN', 0, 1),
    (PATTERN, 'MAIN', 1, 2),
    (TERM, 'MAIN', 0, 1),
    (TERM, 'MAIN', 1, 1),
    (NONTERMINAL, 'MAIN', 0, 1),
    (TERMINAL, 'MAIN', 0, 1),
    (TERMINAL, 'MAIN', 1, 1)
)



table = {
    0 : {
        r"#require" : [-1],
        PRODUCTION : [-6],
        LINE : [-7],
        PROGRAM : [-25],
        REQUIRE : [-9],
        r"\w+(\.\w+)*" : [-10],
        GRAMMAR : [-27],
        NONTERMINAL : [-11],
        RULE : [-13]
    },
    1 : {
        NAME : [-2],
        r"\w+(\.\w+)*" : [-5]
    },
    2 : {
        r"as" : [-3],
        r"\n+" : [6],
        EOI : [6]
    },
    3 : {
        NAME : [-4],
        r"\w+(\.\w+)*" : [-5]
    },
    4 : {
        r"\n+" : [7],
        EOI : [7]
    },
    5 : {
        r"\n+" : [8],
        EOI : [8],
        r"as" : [8]
    },
    6 : {
        r"\n+" : [5],
        EOI : [5]
    },
    7 : {
        r"\n+" : [-8],
        EOI : [2]
    },
    8 : {
        r"#require" : [-1],
        PRODUCTION : [-6],
        LINE : [-7],
        REQUIRE : [-9],
        r"\w+(\.\w+)*" : [-10],
        NONTERMINAL : [-11],
        GRAMMAR : [-12],
        RULE : [-13]
    },
    9 : {
        r"\n+" : [4],
        EOI : [4]
    },
    10 : {
        r"\"\S+\"" : [17],
        r"\n+" : [17],
        EOI : [17],
        r"\"\"" : [17],
        r"->" : [17],
        r"\|" : [17],
        r"\w+(\.\w+)*" : [17]
    },
    11 : {
        r"->" : [10]
    },
    12 : {
        EOI : [3]
    },
    13 : {
        r"->" : [-14]
    },
    14 : {
        TERM : [-15],
        PATTERN : [-21],
        r"\w+(\.\w+)*" : [-10],
        TERMINAL : [-17],
        ALTERNATIVES : [-24],
        NONTERMINAL : [-18],
        r"\"\S+\"" : [-19],
        r"\"\"" : [-20]
    },
    15 : {
        TERM : [-15],
        r"\w+(\.\w+)*" : [-10],
        PATTERN : [-16],
        TERMINAL : [-17],
        NONTERMINAL : [-18],
        r"\"\S+\"" : [-19],
        r"\"\"" : [-20],
        r"\n+" : [13],
        EOI : [13],
        r"\|" : [13]
    },
    16 : {
        r"\n+" : [14],
        EOI : [14],
        r"\|" : [14]
    },
    17 : {
        r"\"\S+\"" : [15],
        r"\n+" : [15],
        EOI : [15],
        r"\"\"" : [15],
        r"\|" : [15],
        r"\w+(\.\w+)*" : [15]
    },
    18 : {
        r"\"\S+\"" : [16],
        r"\n+" : [16],
        EOI : [16],
        r"\"\"" : [16],
        r"\|" : [16],
        r"\w+(\.\w+)*" : [16]
    },
    19 : {
        r"\"\S+\"" : [18],
        r"\n+" : [18],
        EOI : [18],
        r"\"\"" : [18],
        r"\|" : [18],
        r"\w+(\.\w+)*" : [18]
    },
    20 : {
        r"\"\S+\"" : [19],
        r"\n+" : [19],
        EOI : [19],
        r"\"\"" : [19],
        r"\|" : [19],
        r"\w+(\.\w+)*" : [19]
    },
    21 : {
        r"\|" : [-22],
        r"\n+" : [11],
        EOI : [11]
    },
    22 : {
        TERM : [-15],
        PATTERN : [-21],
        r"\w+(\.\w+)*" : [-10],
        TERMINAL : [-17],
        NONTERMINAL : [-18],
        r"\"\S+\"" : [-19],
        r"\"\"" : [-20],
        ALTERNATIVES : [-23]
    },
    23 : {
        r"\n+" : [12],
        EOI : [12]
    },
    24 : {
        r"\n+" : [9],
        EOI : [9]
    },
    25 : {
        EOI : [-26]
    },
    26 : {
        None : [0]
    },
    27 : {
        EOI : [1]
    }
}