'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from core import *



def parse(expr: str):
    from core import parse as p
    return Expr(p(expr))



##### bnf #####



from utils import *

import re
import os



class Default:
    """Base class which handles `__eq__` if `__hash__` has been defined by the subclass."""
    def __eq__(self, other): return isinstance(other, type(self)) and self.__hash__() == other.__hash__()


class Terminal(Default):
    def __init__(self, regex: str):
        self.regex = regex.translate({ord("'") : r"\'"})

    def __hash__(self):
        return hash(self.regex)

    def __str__(self):
        return f"'{self.regex}'"

    def __repr__(self):
        return f"r'{self.regex}'"
    

class Nonterminal(Default):
    def __init__(self, rule: str):
        self.rule = rule.upper()

    def __hash__(self):
        return hash(self.rule)
    
    def __len__(self):
        return len(self.rule)

    def __str__(self):
        return self.rule

    def __repr__(self):
        return self.rule


class Production(Default):
    def __init__(self, rule: Nonterminal, module: str, variant: int, pattern: list):
        self.rule = rule
        self.module = module
        self.variant = variant
        self.pattern = pattern
        
    def __hash__(self):
        return hash((self.rule, self.module, self.variant))
    
    def __str__(self):
        return f"{self.rule} ::= {" ".join(map(str, self.pattern))}"
    
    def __repr__(self):
        # return f"ProductionData({self.rule}, {self.module.__repr__()}, {self.variant}, {self.pattern})"
        return f"({self.rule}, {self.module.__repr__()}, {self.variant}, {len(self.pattern)})"


class I(Default):
    def __init__(self, dot: int, production: Production):
        self.dot = dot
        self.production = production
        self.isReduction = (dot == len(production.pattern))
        self.current = (None if self.isReduction else production.pattern[dot])
        self.next = production.pattern[dot+1:]

    def __hash__(self):
        return hash((self.dot, self.production.rule, tuple(self.production.pattern)))
    
    def __repr__(self):
        pattern = self.production.pattern[:]
        pattern.insert(self.dot, "∙")
        return f"{self.production.rule} ::= {" ".join(map(str, pattern))}"


class EPSILON: pass

class START(Nonterminal):
    def __init__(self):
        super().__init__("START")

class EOI(Terminal):
    def __init__(self): super().__init__(str(hash("EOI")))
    
    def __repr__(self): return "EOI"



g_language = get_config("language").lower()
g_modules: dict[str, dict[str, list[list[Terminal|Nonterminal]]]] = {
    g_language : {
        START() : [[Nonterminal("PROGRAM")]]
    }
}
g_grammar: dict[Nonterminal, list[Production]] = {}
g_terminals: set = set()
g_conflicts: str = ""
g_paths: list = [g_language]
g_current_module: dict = {}
g_implementation: str = get_config("implementation")
g_eval: str = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from core import *



def parse(expr: str):
    from core import parse as p
    return Expr(p(expr))



"""



##### eval functions #####



def p_main_bnf_program(expr, module: str = g_language):
    global g_modules 
    global g_current_module
    global g_grammar
    global g_terminals
    global g_conflicts
    global g_paths
    global g_implementation
    global g_eval

    g_current_module = {}

    expr(0)

    if module == g_language: 
        g_modules[module].update(g_current_module)
    else:
        g_modules[module] = g_current_module
        return

    for path in g_paths:

        prefix = f".lib/{path.replace(".", "/")}"

        if not path == g_language:

            # read syntax

            filename = f"{prefix}/{g_implementation}/syntax.txt"
            if not os.path.exists(filename):
                filename = f"{prefix}/syntax.txt"

            with open(filename) as file:
                parse(file.read())(None, path.upper().replace(".", "_"))
        
        # read semantics

        if path == g_language: prefix = get_config("paths", "language")

        filename = f"{prefix}/{g_implementation}/semantics.py"
        if not os.path.exists(filename):
            filename = f"{prefix}/semantics.py"
        
        if not os.path.exists(filename):
            print(f"Semantics not found: {path}")
        else:
            g_eval += f"""##### {path} #####



{embed_eval(filename, path)}
"""
    
    AST = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import *



##### ABSTRACT SYNTAX TREE #####


"""

    for module, grammar in g_modules.items():
        for rule, alternatives in grammar.items():
            if rule not in g_grammar: g_grammar[rule] = []
            for variant, pattern in enumerate(alternatives):
                g_grammar[rule].append(Production(rule, module, variant, pattern))

            AST += f"""
class {rule}(Rule):
    r'''```
{rule} -> {("\n"+" "*(len(rule)+2)+"| ").join(
    " ".join(str(t) for t in pattern) for pattern in alternatives
    )}
    ```'''
"""
    
    AST += f"""

_TERMINALS = {{
    {",\n    ".join((token.__repr__() for token in g_terminals))}
}}


{get_parsetable_str()}
"""
    
    with open("temp/syntax.py", "w") as file:
        file.write(AST)
    with open("temp/semantics.py", "w") as file:
        file.write(g_eval)


def p_main_bnf_grammar_1(expr):
    expr(0)
    expr(2)


def p_main_bnf_require(expr):
    global g_paths

    g_paths.append(expr(0).removeprefix("#require").strip().lower())


def p_main_bnf_production(expr):
    global g_current_module
    
    rule = expr(0)    
    if not rule in g_current_module: g_current_module[rule] = []
    g_current_module[rule].extend(expr(2))


def p_main_bnf_alternatives_0(expr):
    return [list(expr(0))]

def p_main_bnf_alternatives_1(expr):
    return [list(expr(0))] + expr(2)


def p_main_bnf_pattern_0(expr):
    return (expr(0), )

def p_main_bnf_pattern_1(expr):
    return (expr(0), *expr(1))


def p_main_bnf_nonterminal(expr):
    return Nonterminal(expr(0))


def p_main_bnf_terminal_0(expr):
    terminal = Terminal(expr(0)[1:-1])
    g_terminals.add(terminal)
    return terminal

def p_main_bnf_terminal_1(expr):
    return EPSILON()



##### parsing #####



def get_parsetable_str():
    global g_grammar
    global g_modules
    global g_terminals

    automaton: dict[int, dict[I, set]] = {}
    table: dict[int, dict[Terminal|Nonterminal, list[tuple[str, int]]]] = {}

    rules = list(e for opts in g_grammar.values() for e in opts)


    def isNullable(rule: Terminal|Nonterminal|EPSILON) -> bool:
        return (
            isinstance(rule, EPSILON)
            or (
                isinstance(rule, Nonterminal)
                and any(
                    all(isNullable(token) for token in production.pattern)
                    for production in g_grammar[rule]
                )
            )
        )


    def construct_automaton(closure: dict[I, set]):

        def merge(existingState: dict[I, set], newState: dict[I, set]) -> bool:
            if (existingState.keys() == newState.keys()):
                for item, lookahead in newState.items():
                    existingState[item].update(lookahead)
                return True
            return False
            
        state = len(automaton)
        automaton[state] = closure

        for items in get_transitions(automaton[state]).values():

            nextKernel = {
                I(item.dot+1, item.production) : lookahead
                for item, lookahead in items.items()
            }

            nextClosure = construct_closure(nextKernel)
            for closure in automaton.values():
                if merge(closure, nextClosure): break
            else: 
                construct_automaton(nextClosure)

    def construct_closure(kernel: dict[I, set]) -> dict[I, set]:
        
        items: list[tuple[I, set]] = []

        expansions = list(kernel.items())

        while expansions:

            # add the most recent rule to the expansion
            item, lookahead = expansions.pop()

            if (item, lookahead) in items: continue

            items.append((item, lookahead))

            # if the current token is a nonterminal, we must add further expansions
            if isinstance(item.current, Nonterminal):
                
                newLookahead = FIRST(item.next, lookahead)

                for productionData in g_grammar[item.current]:
                    expansions.append((I(0, productionData), newLookahead))

        out: dict[I, set] = {}

        for (item, lookahead) in items:
            if item in out:
                out[item].update(lookahead)
            else:
                out[item] = lookahead

        return out
    
    def get_transitions(state: dict[I, set]) -> dict[Terminal|Nonterminal, dict[I, set]]:
        transitions = {}

        for item, lookahead in state.items():
            if item.isReduction: continue

            if not item.current in transitions: transitions[item.current] = {}

            transitions[item.current][item] = lookahead

        return transitions
    
    def FIRST(sequence: list[Terminal|Nonterminal], lookahead: set = None, exclude: set = None) -> set[str]:
    
        exclude = exclude or set()
        first = set()

        for token in sequence:
            if isinstance(token, Terminal):
                first.add(token)
                break

            elif not token in exclude:
                for production in g_grammar[token]: 
                    first.update(FIRST(production.pattern, set(), exclude.union({token})))
                
                if isNullable(token): continue
                else: break

        else: first.update(lookahead)

        return first
    
    def construct_table() -> str:
        """Constructs the LALR table."""

        conflicts = {}

        for state, closure in automaton.items():
            table[state] = {}

            transitions = get_transitions(closure)
            reductions = { item : lookahead for item, lookahead in closure.items() if item.isReduction }

            for item, lookahead in reductions.items():
                for token in lookahead:
                    table[state][token] = table[state].get(token, set()).union({
                        ("A", True) if (item.production.rule, token) == (START(), EOI())
                        else ("R", rules.index(item.production))
                    })

            for token, kernel in transitions.items():
                nextItems = {
                        I(item.dot+1, item.production)
                        for item in kernel
                    }
                action = ("S" if isinstance(token, Terminal) else "G")
                
                table[state][token] = table[state].get(token, set()).union({ 
                        (action, toState) for toState, toClosure in automaton.items() if nextItems.issubset(toClosure)
                    })

            for token, actions in table[state].items():
                table[state][token] = list(sorted(actions, key=lambda tup: tup[0] == "R"))
                
                if len(actions) > 1:
    
                    if not state in conflicts:
                        conflicts[state] = {}

                    conflict = "/".join(action[0] for action in table[state][token])

                    if not conflict in conflicts:
                        conflicts[state][conflict] = []
                    
                    conflicts[state][conflict].append(token)

        global g_conflicts

        if conflicts: 
            g_conflicts = f"Found {len(conflicts)} conflicts."
            for state, conflictTypes in conflicts.items():
                for label, tokens in conflictTypes.items():
                    g_conflicts += f"\n(state {state}) {label} conflict on token{"s"*(len(tokens) != 1)} {", ".join(token.__repr__() for token in tokens)}"
        else:
            g_conflicts = "No conflicts found."
    
    

    construct_automaton(construct_closure({
        I(0, Production(START(), "MAIN", 0, [Nonterminal("PROGRAM")])) : { EOI() } 
        }))
    construct_table()
    
    return f"""
##### PARSETABLE #####



# ---{{ GRAMMAR }}---
{"\n".join(f"# Rule {i:<4} {str(rule)}" for i, rule in enumerate(rules))}


    
# Parsetable constructed with {len(table)} state{"s"*(len(table)!=1)}.
# {g_conflicts.replace("\n", "\n# ")}



_RULES = (
    {",\n    ".join(rule.__repr__() for rule in rules)}
)



_TABLE = {{
    {",\n    ".join(f"""{state} : {{
        {",\n        ".join(f"{token.__repr__()} : {actions}" for token, actions in transitions.items())}
    }}""" for state, transitions in table.items())}
}}"""


def embed_eval(filename: str, path: str) -> str:
    
    def replace_fname(match: re.Match) -> str:
        return f"p_{path.replace("/", "_")}_{match.group().removeprefix("p_")}"

    with open(filename) as file:
        text = file.read()

        print(f"embedding {path}")
        return re.sub(
            pattern=r"\bp_\w+",
            repl=replace_fname,
            string=text
        )

