from datatypes import *
from utils import *

import functools
import os



MAIN = "MAIN"
Nonterminal.MAIN = MAIN
NEWLINES = False
INDENTATION = False
MODULE: dict = MAIN
PATHS: list = [MAIN]
ALIASES: dict = {}
REFERENCES: dict = {}
DECLARATIONS: dict = {}
GRAMMAR: dict[Nonterminal, list[Production]] = {
    START() : [ Production(START(), MAIN, 0, [Nonterminal("PROGRAM"), EOI()]) ]
}
TERMINALS: set[Terminal] = set()
CONFLICTS: str = ""
WARNINGS: dict = {
    "syntax" : {},
    "semantics" : {}
}
EVAL: str = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule as __Rule__
from datatypes import Token as __Token__

from collections.abc import Sequence as __Sequence__



"""



##### eval functions #####



def p_program(expr, module: str = MAIN):
    from compiler import parse

    
    global MODULE
    global PATHS
    global ALIASES
    global REFERENCES
    global DECLARATIONS
    global GRAMMAR
    global TERMINALS
    global CONFLICTS
    global WARNINGS
    global EVAL


    def get_filename(directory: str, file: str):
        """Tries to find a syntax/semantics file in the given directory."""
        
        filename = f"{directory}/{CONFIG.implementation}/{file}"
        
        if not os.path.exists(filename):
            filename = f"{directory}/{file}"
        
        if not os.path.exists(filename):
            filename = None

            category = file.split(".")[0]
            subcategory = (MAIN if module == MAIN else "dependency")
            if subcategory not in WARNINGS[category]: WARNINGS[category][subcategory] = []
            WARNINGS[category][subcategory].append(directory)
        
        return filename
        

    ALIASES[module] = {}
    REFERENCES[module] = set()
    DECLARATIONS[module] = set()

    MODULE = module
    expr(0)
    MODULE = module

    # Execution after this point only happens once, in the main module. 
    if module != MAIN: return

    print("Metacompiling") if CONFIG.flags.metacompile else print(f"Compiling" + (" onefile" if CONFIG.flags.onefile else ""))
    print()

    if INDENTATION:
        for NT, T in (
                (Nonterminal(dereference("INDENT")), Terminal(CONFIG.formatting.indent)),
                (Nonterminal(dereference("DEDENT")), Terminal(CONFIG.formatting.dedent))
            ): 
            GRAMMAR[NT] = [Production(NT, MAIN, 0, [T])]
            TERMINALS.add(T)

    for path in PATHS:

        directory = CONFIG.paths.language if (path == MAIN) else os.path.join(CONFIG.paths.lib, path)
        modulename = toModule(path)

        if not path == MAIN:

            # read syntax; syntax for main module handled by default
            filename = get_filename(directory, "syntax.txt")
            if filename is not None:
                with open(filename) as file:
                    __Expr__(parse(file.read()))(None, modulename)
            
        # read semantics
        filename = get_filename(directory, "semantics.py")
        
        if (filename is None) and (path == MAIN): CONFIG.implementation = "compiler"
        
        if filename is not None:
            EVAL += f"""##### {path} #####



{embed_eval(filename, modulename)}


"""
            
    AST = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, EOI



##### AST #####



"""

    for category, warnings in WARNINGS.items(): 
        print_warnings(f"{category} not found", warnings)

    for rule in GRAMMAR:
        AST += f"class {rule}(Rule):None\n"
    
    AST += get_parsetable_str()
    
    EVAL += f"""##### evaluation #####



class __Expr__(__Sequence__):
    \"""Immutable, callable `Sequence` object which returns its elements as instances of itself.\"""

    SEMANTICS = {{ fname : func for fname, func in globals().items() if fname.startswith("p_")}}

    def __new__(cls, node):
        return (
            super().__new__(cls) if isinstance(node, __Rule__)
            else node.tok if isinstance(node, __Token__)
            else node
        )
        
    def __init__(self, node: __Rule__):
        self._children = node.children
        self._node = node

    def __getitem__(self, index: int|slice):
        item = self._children[index]
        if isinstance(index, slice):
            return tuple(__Expr__(e) for e in item)
        return __Expr__(item)
  
    def __len__(self):
        return len(self._children)

    def __str__(self):
        return self._node.__str__()

    def __repr__(self):
        return self._node.__repr__()

    def __call__(self, i: int = None, *args, **kwargs):
        e = self if (i == None) else self[i]
        return self.evaluate(e, *args, **kwargs)

    def default(self, x: '__Expr__'):
        return {"x(0)" if (CONFIG.implementation == "interpreter") else "\"\".join(x(i) for i in range(len(x)))"}

    def get_function(self, node: __Rule__):
        return (
            __Expr__.SEMANTICS.get(node.fname_var)
            or __Expr__.SEMANTICS.get(node.fname)
            or self.default
        )

    def evaluate(self, expr, *args, **kwargs):
        return (
            self.get_function(expr._node)(expr, *args, **kwargs) if isinstance(expr, __Expr__)
            else expr
        )
"""

    if CONFIG.flags.metacompile:
        with open(os.path.join(CONFIG.paths.root, "compiler/parserdata.py"), "w") as file:
            file.write(AST)
        with open(os.path.join(CONFIG.paths.root, "compiler/evaluation.py"), "w") as file:
            file.write(EVAL.strip() + "\n")
    else:
        with open(os.path.join(CONFIG.paths.root, "parser/parserdata.py"), "w") as file:
            file.write(AST)
        with open(os.path.join(CONFIG.paths.root, "parser/evaluation.py"), "w") as file:
            file.write(EVAL.strip() + "\n")


def p_grammar_1(expr):
    expr(0)
    expr(2)


def p_require(expr):
    path = toPath(expr(1))

    ref = (expr(3) if len(expr) > 2 else path)
    ALIASES[MODULE][toModule(ref)] = toModule(path)
    
    components = path.split("/")
    paths = list("/".join(components[:i+1]) for i in range(len(components)))
    for path in paths:
        if not path in PATHS:
            PATHS.append(path)


def p_production(expr):    
    rule = expr(0)
    declare(rule)
    alternatives = expr(2)

    if not rule in GRAMMAR: GRAMMAR[rule] = []
    for variant, pattern in enumerate(alternatives):
        GRAMMAR[rule].append(Production(rule, MODULE, variant, pattern))


def p_alternatives_0(expr):
    return [list(expr(0))]

def p_alternatives_1(expr):
    return [list(expr(0))] + expr(2)


def p_pattern_0(expr):
    return (expr(0), )

def p_pattern_1(expr):
    return (expr(0), *expr(1))


def p_nonterminal(expr):
    global INDENTATION

    nonterminal = Nonterminal(dereference(expr(0)))
    reference(nonterminal)
    INDENTATION = INDENTATION or (nonterminal.name in ("INDENT", "DEDENT"))
    
    return nonterminal


def p_terminal_0(expr):
    global NEWLINES
    
    terminal = Terminal(expr(0)[1:-1])
    NEWLINES = NEWLINES or (r"\n" in terminal.regex)
    TERMINALS.add(terminal)
    
    return terminal


def p_terminal_1(expr):
    return EPSILON()



def dereference(name: str) -> tuple:
    module, name = "", name
    if "." in name: module, name = name.rsplit(".", 1)
    module, name = toModule(module), toModule(name)
    module = ALIASES[MODULE].get(module, module) or MODULE
    
    return (module, name)


def reference(rule: Nonterminal):
    REFERENCES[MODULE].add(rule)


def declare(rule: Nonterminal):
    DECLARATIONS[MODULE].add(rule)


def sfilter(s: str, exclude: tuple) -> str:
    replace = {".", "/", "_"}.difference(exclude).pop()
    return s.translate({ ord(e) : replace for e in exclude })

def toModule(s: str) -> str:
    return sfilter(s, {".", "/"}).upper()

def toPath(s: str) -> str:
    return sfilter(s, {".", "_"}).lower()

def toRequirement(s: str) -> str:
    return sfilter(s, {"/", "_"}).lower()
    


##### parsing #####



def get_parsetable_str():
    global GRAMMAR
    global TERMINALS
    global CONFLICTS


    rules = list(e for opts in GRAMMAR.values() for e in opts)

    COLLECTION: list[set[Item]] = []
    GOTO: dict[int, dict[Terminal|Nonterminal, int]] = {}
    X: set[tuple[int, Nonterminal]] = set()
    

    def CANONICAL(itemset: set[Item]) -> dict:
        """Compute the canonical LR(0) collection."""

        state = len(COLLECTION)
        GOTO[state] = {}
        COLLECTION.append(itemset)
        for token, closure in GOTOS(itemset).items():
            if closure in COLLECTION:
                GOTO[state][token] = COLLECTION.index(closure)
            else:
                GOTO[state][token] = len(COLLECTION)
                CANONICAL(closure)
            if isinstance(token, Nonterminal): X.add((state, token))


    def CLOSURE(kernel: set[Item]) -> set[Item]:
        """Compute the closure of an LR(0) kernel."""

        closure = set()
        expansions = kernel
        while expansions:
            item = expansions.pop()
            if item not in closure:
                closure.add(item)
                if isinstance(item.current, Nonterminal):
                    for production in GRAMMAR[item.current]:
                        expansions.add(Item(0, production))
        return closure
    

    def GOTOS(itemset: set[Item]) -> dict[Terminal|Nonterminal, set[Item]]:
        """Compute the goto transitions of a given state."""

        gotos: dict[Terminal|Nonterminal, set[Item]] = {}
        for item in itemset:
            if item.isReduction: continue
            if item.current not in gotos: gotos[item.current] = set()
            gotos[item.current].add(Item(item.dot+1, item.production))
        return { token : CLOSURE(kernel) for token, kernel in gotos.items() }


    def LOOKAHEADS() -> dict[tuple[int, Production], set[Terminal]]:
        """LALR lookahead computation algorithm, adapted from (DeRemer and Penello, 1982).
        Accessible via the ACM Digital Library: https://dl.acm.org/doi/epdf/10.1145/69622.357187.
        """
        
        nonlocal X


        def accesses(p: int, sequence: list[Terminal|Nonterminal]) -> int|None:
            """Applies a sequence of transitions from state p, returning the resultant state or `None`."""
            for t in sequence:
                try: p = GOTO[p][t]
                except: return None
            return p
        

        DR: dict[tuple[int, Nonterminal], set[Terminal]] = { transition : set() for transition in X }
        reads: dict[tuple[int, Nonterminal], list[tuple[int, Nonterminal]]] = { transition : [] for transition in X }
        includes: dict[tuple[int, Nonterminal], list[tuple[int, Nonterminal]]] = { transition : [] for transition in X }
        lookback: dict[tuple[int, Production], list[tuple[int, Nonterminal]]] = {}
                
        for (p, A) in X:
            q = GOTO[p][A]
            for B in GOTO[q]:
                # direct read
                if isinstance(B, Terminal):
                    DR[(p, A)].add(B)
                # reads relation
                elif isinstance(B, Nonterminal) and NULLABLE(B):
                    reads[(p, A)].append((q, B))

            for production in GRAMMAR[A]:
                # includes relation
                nullable = True
                # enumerating backwards allows us to stop iteration at the first nonnullable token
                for i, B in enumerate(reversed(production.pattern)):
                    if isinstance(B, Nonterminal):
                        q = accesses(p, production.pattern[:-(i+1)])
                        if q is not None: includes[(q, B)].append((p, A))
                        if not nullable: break
                        nullable = NULLABLE(B)
                    else: break
                # lookback relation
                q = accesses(p, production.pattern)
                if q is not None:
                    if not (q, production) in lookback: lookback[(q, production)] = []
                    lookback[(q, production)].append((p, A))


        Read = DIGRAPH(reads, DR)
        Follow = DIGRAPH(includes, Read)

        LA: dict[tuple, set] = {}
        for look, lookbacks in lookback.items():
            LA[look] = set()
            for back in lookbacks:
                LA[look].update(Follow[back])

        return LA


    def DIGRAPH(
            R: dict[tuple[int, Nonterminal], list[tuple[int, Nonterminal]]], 
            f: dict[tuple[int, Nonterminal], set[Terminal]]
        ) -> dict[tuple[int, Nonterminal], set[Terminal]]:
        """The DeRemer-Penello Digraph algorithm.
        
        :param R: A relation on X.
        :param f: A set-valued function.
        :returns F: A function from X to sets."""

        F: dict[tuple[int, Nonterminal], set[Terminal]] = {}
        S: list[tuple[int, Nonterminal]] = []
        N: dict[tuple[int, Nonterminal], int] = dict.fromkeys(X, 0)
        
        def TRAVERSE(x):
            S.append(x)
            d = len(S)
            N[x] = d
            F[x] = f[x]
            for y in R[x]:
                if N[y] == 0: TRAVERSE(y)
                N[x] = min(N[x], N[y])
                F[x].update(F[y])
            if N[x] == d:
                while True:
                    N[S[-1]] = float('inf')
                    F[S[-1]] = F[x]
                    if S.pop() == x: break
    
        for x in X:
            if N[x] == 0:
                TRAVERSE(x)

        return F
    

    @functools.cache
    def NULLABLE(rule: Terminal|Nonterminal, exclude: tuple = None) -> bool:
        exclude = exclude or tuple()
        return (
            isinstance(rule, Nonterminal)
            and any(
                (production.pattern == [])
                or all(NULLABLE(token, tuple((rule, *exclude))) for token in production.pattern if not token in exclude)
                for production in GRAMMAR[rule]
            )
        )


    def REDUCTIONS(p: int) -> dict:
        out = {}
        for item in COLLECTION[p]:
            if item.isReduction:
                lookaheads = LA.get((p, item.production))
                if not item.production in out: out[item.production] = set()
                if lookaheads is None:
                    out[item.production].add(None)
                else:
                    out[item.production].update(lookaheads)
        return out
    

    CANONICAL(CLOSURE({ Item(0, GRAMMAR[START()][0]) }))


    LA: dict[tuple[int, Production], set[Terminal]] = LOOKAHEADS()
    TABLE = {}
    conflicts = {}


    for p in range(len(COLLECTION)):
        TABLE[p] = {}
        for t, q in GOTO[p].items():
            if not t in TABLE[p]: TABLE[p][t] = []
            TABLE[p][t].append(-q)
        for A, lookaheads in REDUCTIONS(p).items():
            for t in lookaheads:
                if not t in TABLE[p]: TABLE[p][t] = []
                TABLE[p][t].append(rules.index(A))

        for token, actions in TABLE[p].items():            
            if len(actions) > 1:
                if not p in conflicts:
                    conflicts[p] = {}

                conflict = "/".join(("S" if action > 0 else "R" if action < 0 else "A") for action in TABLE[p][token])

                if not conflict in conflicts:
                    conflicts[p][conflict] = []
                
                conflicts[p][conflict].append(token)

        if conflicts: 
            CONFLICTS = f"Found {len(conflicts)} conflicts."
            for p, conflictTypes in conflicts.items():
                for label, tokens in conflictTypes.items():
                    CONFLICTS += f"\n(state {p}) {label} conflict on token{"s"*(len(tokens) != 1)} {", ".join(token.__repr__() for token in tokens)}"
        else:
            CONFLICTS = "No conflicts found."
    

    if CONFIG.flags.verbose:
            print(CONFLICTS)
            print()

            from statistics import mean, median, mode
            sets = tuple(
                tuple(
                    regex for regex in state.keys() 
                    if isinstance(regex, Terminal) and not isinstance(regex, EOI)) for state in TABLE.values()
                )
            data = tuple(map(len, sets))

            print(f"""Scanner set optimization data

Original    : {len(TERMINALS)}
Average     : {mean(data):.3f}
Reduction   : {(1-mean(data)/len(TERMINALS))*100:.3f}%

Minimum     : {min(data)}
Median      : {median(data)}
Maximum     : {max(data)}

Mode : {mode(data)}

NULLABLE cache: {NULLABLE.cache_info()}
""")

    
    grammar = f"""--------{{ GRAMMAR }}--------
{"\n".join(f"Rule {i:<3} {str(rule)}" for i, rule in enumerate(rules))}"""

    if CONFIG.flags.debug: 
        print(grammar)
        print()

        categories = [*sorted(TERMINALS, key=str), EOI(), *GRAMMAR.keys()]
        categories.remove(START())
        parsetable = displayTable(
            title="LALR Table", 
            columns=dict.fromkeys(("State", *map(str, categories)), {})
            )
        for state, options in TABLE.items():
            row = [str(state)]
            for token in categories:
                data = options.get(token, [None])[0]
                action = (
                "ERR" if data is None
                else "S" if data > 0
                else "R" if data < 0
                else "ACC"
                )
                if data: data = str(abs(data))
                row.append("" if data is None else f"{action} {data}")
            parsetable.add_row(*row)
            
        
        print("------{ AUTOMATON }------")
        for p, closure in enumerate(COLLECTION):
            print(f"State {p}")
            for item in closure:
                print(f"    {item}")
            print()

        print(parsetable)


    return f"""


##### PARSETABLE #####



# {str(grammar).replace("\n", "\n# ")}



# Parsetable constructed with {len(TABLE)} state{"s"*(len(TABLE)!=1)}.
# {CONFLICTS.replace("\n", "\n# ")}



indentation = {INDENTATION}
newlines = {NEWLINES}



rules = (
    {",\n    ".join(rule.__repr__() for rule in rules)}
)



table = {{
    {",\n    ".join(f"""{state} : {{
        {",\n        ".join(f"{token.__repr__()} : {actions}" for token, actions in transitions.items())}
    }}""" for state, transitions in TABLE.items())}
}}"""


def embed_eval(filename: str, modulename: str) -> str:
    from re import Match
    from re import sub

    def replace_fname(match: Match) -> str:
        return f"p_{modulename}_{match.group().removeprefix("p_")}".lower()

    with open(filename) as file:
        return sub(
            pattern=r"p_\w*\(",
            repl=replace_fname,
            string=file.read()
        )
