from AST import *


        
RULES = (
    ProductionData( # <START> ::= <PROGRAM>
            START, 'MAIN', 0, [PROGRAM]),
    ProductionData( # <PROGRAM> ::= <EXPRESSION>
            PROGRAM, 'MAIN', 1, [EXPRESSION]),
    ProductionData( # <PROGRAM> ::= <STATEMENT_LIST>
            PROGRAM, 'MAIN', 0, [STATEMENT_LIST]),
    ProductionData( # <STATEMENT_LIST> ::= <STATEMENT>
            STATEMENT_LIST, 'MAIN', 0, [STATEMENT]),
    ProductionData( # <STATEMENT_LIST> ::= <STATEMENT> \n+ <STATEMENT_LIST>
            STATEMENT_LIST, 'MAIN', 1, [STATEMENT, r'\n+', STATEMENT_LIST]),
    ProductionData( # <STATEMENT> ::= <CONDITIONAL>
            STATEMENT, 'MAIN', 1, [CONDITIONAL]),
    ProductionData( # <STATEMENT> ::= <MARKER>
            STATEMENT, 'MAIN', 4, [MARKER]),
    ProductionData( # <STATEMENT> ::= <GOTO>
            STATEMENT, 'MAIN', 3, [GOTO]),
    ProductionData( # <STATEMENT> ::= <ASSIGNMENT>
            STATEMENT, 'MAIN', 0, [ASSIGNMENT]),
    ProductionData( # <STATEMENT> ::= <PRINT>
            STATEMENT, 'MAIN', 5, [PRINT]),
    ProductionData( # <STATEMENT> ::= <RETURN>
            STATEMENT, 'MAIN', 2, [RETURN]),
    ProductionData( # <EXPRESSION> ::= <MATHEXPR>
            EXPRESSION, 'MAIN', 0, [MATHEXPR]),
    ProductionData( # <VALUE> ::= <NUMBER>
            VALUE, 'MATH_INFIX', 0, [NUMBER]),
    ProductionData( # <VALUE> ::= <STRING>
            VALUE, 'MAIN', 0, [STRING]),
    ProductionData( # <VALUE> ::= <LABEL>
            VALUE, 'MAIN', 1, [LABEL]),
    ProductionData( # <VALUE> ::= <BOOL>
            VALUE, 'MAIN', 2, [BOOL]),
    ProductionData( # <LABEL> ::= <ID>
            LABEL, 'MAIN', 0, [ID]),
    ProductionData( # <BOOL> ::= True
            BOOL, 'MAIN', 0, [r'True']),
    ProductionData( # <BOOL> ::= False
            BOOL, 'MAIN', 1, [r'False']),
    ProductionData( # <BOOL> ::= True
            BOOL, 'DATATYPES_NUMERIC', 0, [r'True']),
    ProductionData( # <BOOL> ::= False
            BOOL, 'DATATYPES_NUMERIC', 1, [r'False']),
    ProductionData( # <ASSIGNMENT> ::= let <ID> be <EXPRESSION>
            ASSIGNMENT, 'MAIN', 0, [r'let', ID, r'be', EXPRESSION]),
    ProductionData( # <CONDITIONAL> ::= <IF_THEN>
            CONDITIONAL, 'MAIN', 0, [IF_THEN]),
    ProductionData( # <CONDITIONAL> ::= <IF_THEN_ELSE>
            CONDITIONAL, 'MAIN', 1, [IF_THEN_ELSE]),
    ProductionData( # <IF_THEN> ::= if <COMPARISON> , then <BLOCK>
            IF_THEN, 'MAIN', 0, [r'if', COMPARISON, r',', r'then', BLOCK]),
    ProductionData( # <IF_THEN_ELSE> ::= if <COMPARISON> , then <BLOCK> \n+ else <BLOCK>
            IF_THEN_ELSE, 'MAIN', 0, [r'if', COMPARISON, r',', r'then', BLOCK, r'\n+', r'else', BLOCK]),
    ProductionData( # <INDENT> ::= //INDENTATION-MARKER//
            INDENT, 'MAIN', 0, [r'//INDENTATION-MARKER//']),
    ProductionData( # <DEDENT> ::= //DEDENTATION-MARKER//
            DEDENT, 'MAIN', 0, [r'//DEDENTATION-MARKER//']),
    ProductionData( # <BLOCK> ::= \n+ <INDENT> <STATEMENT_LIST> <DEDENT>
            BLOCK, 'MAIN', 0, [r'\n+', INDENT, STATEMENT_LIST, DEDENT]),
    ProductionData( # <RETURN> ::= return <EXPRESSION>
            RETURN, 'MAIN', 0, [r'return', EXPRESSION]),
    ProductionData( # <GOTO> ::= goto instruction <MARK>
            GOTO, 'MAIN', 0, [r'goto', r'instruction', MARK]),
    ProductionData( # <MARKER> ::= @ <MARK> \n+ <STATEMENT_LIST>
            MARKER, 'MAIN', 0, [r'@', MARK, r'\n+', STATEMENT_LIST]),
    ProductionData( # <MARK> ::= <ID>
            MARK, 'MAIN', 0, [ID]),
    ProductionData( # <MARK> ::= <NUMBER>
            MARK, 'MAIN', 1, [NUMBER]),
    ProductionData( # <PRINT> ::= print <EXPRESSION>
            PRINT, 'MAIN', 0, [r'print', EXPRESSION]),
    ProductionData( # <PRINT> ::= print
            PRINT, 'MAIN', 1, [r'print']),
    ProductionData( # <ID> ::= [_a-zA-Z][_a-zA-Z0-9]*
            ID, 'DATATYPES_IDENTIFIER', 0, [r'[_a-zA-Z][_a-zA-Z0-9]*']),
    ProductionData( # <STRING> ::= "[^"\n]*"
            STRING, 'DATATYPES_STRING', 0, [r'"[^"\n]*"']),
    ProductionData( # <NUMBER> ::= <INT>
            NUMBER, 'DATATYPES_NUMERIC', 0, [INT]),
    ProductionData( # <NUMBER> ::= <FLOAT>
            NUMBER, 'DATATYPES_NUMERIC', 1, [FLOAT]),
    ProductionData( # <NUMBER> ::= <BOOL>
            NUMBER, 'DATATYPES_NUMERIC', 2, [BOOL]),
    ProductionData( # <INT> ::= 0
            INT, 'DATATYPES_NUMERIC', 0, [r'0']),
    ProductionData( # <INT> ::= [1-9]\d*
            INT, 'DATATYPES_NUMERIC', 1, [r'[1-9]\d*']),
    ProductionData( # <FLOAT> ::= \d*\.\d+
            FLOAT, 'DATATYPES_NUMERIC', 0, [r'\d*\.\d+']),
    ProductionData( # <MATHEXPR> ::= <ADD>
            MATHEXPR, 'MATH_INFIX', 0, [ADD]),
    ProductionData( # <MATHEXPR> ::= <SUBTRACT>
            MATHEXPR, 'MATH_INFIX', 1, [SUBTRACT]),
    ProductionData( # <MATHEXPR> ::= <TERM>
            MATHEXPR, 'MATH_INFIX', 2, [TERM]),
    ProductionData( # <MATHEXPR> ::= <COMPARISON>
            MATHEXPR, 'MATH_INFIX', 3, [COMPARISON]),
    ProductionData( # <ADD> ::= <MATHEXPR> \+ <TERM>
            ADD, 'MATH_INFIX', 0, [MATHEXPR, r'\+', TERM]),
    ProductionData( # <SUBTRACT> ::= <MATHEXPR> - <TERM>
            SUBTRACT, 'MATH_INFIX', 0, [MATHEXPR, r'-', TERM]),
    ProductionData( # <TERM> ::= <MULTIPLY>
            TERM, 'MATH_INFIX', 0, [MULTIPLY]),
    ProductionData( # <TERM> ::= <DIVIDE>
            TERM, 'MATH_INFIX', 1, [DIVIDE]),
    ProductionData( # <TERM> ::= <FACTOR>
            TERM, 'MATH_INFIX', 2, [FACTOR]),
    ProductionData( # <MULTIPLY> ::= <TERM> \* <FACTOR>
            MULTIPLY, 'MATH_INFIX', 0, [TERM, r'\*', FACTOR]),
    ProductionData( # <DIVIDE> ::= <TERM> / <FACTOR>
            DIVIDE, 'MATH_INFIX', 0, [TERM, r'/', FACTOR]),
    ProductionData( # <FACTOR> ::= \( <MATHEXPR> \)
            FACTOR, 'MATH_INFIX', 0, [r'\(', MATHEXPR, r'\)']),
    ProductionData( # <FACTOR> ::= <VALUE>
            FACTOR, 'MATH_INFIX', 1, [VALUE]),
    ProductionData( # <COMPARISON> ::= <GE>
            COMPARISON, 'MATH_INFIX', 2, [GE]),
    ProductionData( # <COMPARISON> ::= <NEQ>
            COMPARISON, 'MATH_INFIX', 5, [NEQ]),
    ProductionData( # <COMPARISON> ::= <EQ>
            COMPARISON, 'MATH_INFIX', 4, [EQ]),
    ProductionData( # <COMPARISON> ::= <LEQ>
            COMPARISON, 'MATH_INFIX', 1, [LEQ]),
    ProductionData( # <COMPARISON> ::= <LE>
            COMPARISON, 'MATH_INFIX', 0, [LE]),
    ProductionData( # <COMPARISON> ::= <GEQ>
            COMPARISON, 'MATH_INFIX', 3, [GEQ]),
    ProductionData( # <LE> ::= <MATHEXPR> < <MATHEXPR>
            LE, 'MATH_INFIX', 0, [MATHEXPR, r'<', MATHEXPR]),
    ProductionData( # <LEQ> ::= <MATHEXPR> <= <MATHEXPR>
            LEQ, 'MATH_INFIX', 0, [MATHEXPR, r'<=', MATHEXPR]),
    ProductionData( # <GE> ::= <MATHEXPR> > <MATHEXPR>
            GE, 'MATH_INFIX', 0, [MATHEXPR, r'>', MATHEXPR]),
    ProductionData( # <GEQ> ::= <MATHEXPR> >= <MATHEXPR>
            GEQ, 'MATH_INFIX', 0, [MATHEXPR, r'>=', MATHEXPR]),
    ProductionData( # <EQ> ::= <MATHEXPR> == <MATHEXPR>
            EQ, 'MATH_INFIX', 0, [MATHEXPR, r'==', MATHEXPR]),
    ProductionData( # <NEQ> ::= <MATHEXPR> != <MATHEXPR>
            NEQ, 'MATH_INFIX', 0, [MATHEXPR, r'!=', MATHEXPR])
)



TABLE = { 
    0 : {
        PROGRAM : [('G', 1)],
        STATEMENT_LIST : [('G', 2)],
        STATEMENT : [('G', 3)],
        RETURN : [('G', 6)],
        r'return' : [('S', 7)],
        PRINT : [('G', 61)],
        r'print' : [('S', 62)],
        ASSIGNMENT : [('G', 64)],
        r'let' : [('S', 65)],
        GOTO : [('G', 69)],
        r'goto' : [('S', 70)],
        MARKER : [('G', 76)],
        r'@' : [('S', 77)],
        CONDITIONAL : [('G', 81)],
        IF_THEN_ELSE : [('G', 82)],
        r'if' : [('S', 83)],
        IF_THEN : [('G', 96)],
        EXPRESSION : [('G', 99)],
        MATHEXPR : [('G', 9)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    1 : {
        EOI : [('A', True)]
    },
    2 : {
        EOI : [('R', 2)]
    },
    3 : {
        r'\n+' : [('S', 4), ('R', 3)],
        r'//DEDENTATION-MARKER//' : [('R', 3)],
        EOI : [('R', 3)]
    },
    4 : {
        STATEMENT_LIST : [('G', 5)],
        STATEMENT : [('G', 3)],
        RETURN : [('G', 6)],
        r'return' : [('S', 7)],
        PRINT : [('G', 61)],
        r'print' : [('S', 62)],
        ASSIGNMENT : [('G', 64)],
        r'let' : [('S', 65)],
        GOTO : [('G', 69)],
        r'goto' : [('S', 70)],
        MARKER : [('G', 76)],
        r'@' : [('S', 77)],
        CONDITIONAL : [('G', 81)],
        IF_THEN_ELSE : [('G', 82)],
        r'if' : [('S', 83)],
        IF_THEN : [('G', 96)]
    },
    5 : {
        r'\n+' : [('R', 4)],
        r'//DEDENTATION-MARKER//' : [('R', 4)],
        EOI : [('R', 4)]
    },
    6 : {
        r'\n+' : [('R', 10)],
        EOI : [('R', 10)],
        r'//DEDENTATION-MARKER//' : [('R', 10)]
    },
    7 : {
        EXPRESSION : [('G', 8)],
        MATHEXPR : [('G', 9)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    8 : {
        r'\n+' : [('R', 29)],
        EOI : [('R', 29)],
        r'//DEDENTATION-MARKER//' : [('R', 29)]
    },
    9 : {
        r'\n+' : [('R', 11)],
        EOI : [('R', 11)],
        r'//DEDENTATION-MARKER//' : [('R', 11)],
        r'>' : [('S', 10)],
        r'!=' : [('S', 12)],
        r'==' : [('S', 14)],
        r'<=' : [('S', 16)],
        r'<' : [('S', 18)],
        r'\+' : [('S', 20)],
        r'-' : [('S', 41)],
        r'>=' : [('S', 48)]
    },
    10 : {
        MATHEXPR : [('G', 11)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    11 : {
        r'>' : [('S', 10), ('R', 65)],
        EOI : [('R', 65)],
        r'!=' : [('S', 12), ('R', 65)],
        r'<=' : [('S', 16), ('R', 65)],
        r'\)' : [('R', 65)],
        r'>=' : [('S', 48), ('R', 65)],
        r'\n+' : [('R', 65)],
        r',' : [('R', 65)],
        r'<' : [('S', 18), ('R', 65)],
        r'\+' : [('S', 20), ('R', 65)],
        r'==' : [('S', 14), ('R', 65)],
        r'//DEDENTATION-MARKER//' : [('R', 65)],
        r'-' : [('S', 41), ('R', 65)]
    },
    12 : {
        MATHEXPR : [('G', 13)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    13 : {
        r'>' : [('S', 10), ('R', 68)],
        EOI : [('R', 68)],
        r'!=' : [('S', 12), ('R', 68)],
        r'<=' : [('S', 16), ('R', 68)],
        r'\)' : [('R', 68)],
        r'>=' : [('S', 48), ('R', 68)],
        r'\n+' : [('R', 68)],
        r',' : [('R', 68)],
        r'<' : [('S', 18), ('R', 68)],
        r'\+' : [('S', 20), ('R', 68)],
        r'==' : [('S', 14), ('R', 68)],
        r'-' : [('S', 41), ('R', 68)]
    },
    14 : {
        MATHEXPR : [('G', 15)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    15 : {
        r'>' : [('S', 10), ('R', 67)],
        EOI : [('R', 67)],
        r'!=' : [('S', 12), ('R', 67)],
        r'<=' : [('S', 16), ('R', 67)],
        r'\)' : [('R', 67)],
        r'>=' : [('S', 48), ('R', 67)],
        r'\n+' : [('R', 67)],
        r',' : [('R', 67)],
        r'<' : [('S', 18), ('R', 67)],
        r'\+' : [('S', 20), ('R', 67)],
        r'==' : [('S', 14), ('R', 67)],
        r'-' : [('S', 41), ('R', 67)]
    },
    16 : {
        MATHEXPR : [('G', 17)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    17 : {
        r'>' : [('S', 10), ('R', 64)],
        EOI : [('R', 64)],
        r'!=' : [('S', 12), ('R', 64)],
        r'<=' : [('S', 16), ('R', 64)],
        r'\)' : [('R', 64)],
        r'>=' : [('S', 48), ('R', 64)],
        r'\n+' : [('R', 64)],
        r',' : [('R', 64)],
        r'<' : [('S', 18), ('R', 64)],
        r'\+' : [('S', 20), ('R', 64)],
        r'==' : [('S', 14), ('R', 64)],
        r'-' : [('S', 41), ('R', 64)]
    },
    18 : {
        MATHEXPR : [('G', 19)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    19 : {
        r'>' : [('S', 10), ('R', 63)],
        EOI : [('R', 63)],
        r'!=' : [('S', 12), ('R', 63)],
        r'<=' : [('S', 16), ('R', 63)],
        r'\)' : [('R', 63)],
        r'>=' : [('S', 48), ('R', 63)],
        r'\n+' : [('R', 63)],
        r',' : [('R', 63)],
        r'<' : [('S', 18), ('R', 63)],
        r'\+' : [('S', 20), ('R', 63)],
        r'==' : [('S', 14), ('R', 63)],
        r'-' : [('S', 41), ('R', 63)]
    },
    20 : {
        TERM : [('G', 21)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)]
    },
    21 : {
        r'>' : [('R', 48)],
        EOI : [('R', 48)],
        r'!=' : [('R', 48)],
        r'<=' : [('R', 48)],
        r'\)' : [('R', 48)],
        r'>=' : [('R', 48)],
        r'\n+' : [('R', 48)],
        r',' : [('R', 48)],
        r'<' : [('R', 48)],
        r'==' : [('R', 48)],
        r'\+' : [('R', 48)],
        r'-' : [('R', 48)],
        r'\*' : [('S', 22)],
        r'/' : [('S', 43)]
    },
    22 : {
        FACTOR : [('G', 23)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)]
    },
    23 : {
        r'>' : [('R', 53)],
        EOI : [('R', 53)],
        r'!=' : [('R', 53)],
        r'<=' : [('R', 53)],
        r'\)' : [('R', 53)],
        r'>=' : [('R', 53)],
        r'\n+' : [('R', 53)],
        r'\*' : [('R', 53)],
        r'<' : [('R', 53)],
        r'==' : [('R', 53)],
        r'\+' : [('R', 53)],
        r'/' : [('R', 53)],
        r'-' : [('R', 53)]
    },
    24 : {
        r'>' : [('R', 56)],
        EOI : [('R', 56)],
        r'!=' : [('R', 56)],
        r'<=' : [('R', 56)],
        r'\)' : [('R', 56)],
        r'>=' : [('R', 56)],
        r'\n+' : [('R', 56)],
        r'\*' : [('R', 56)],
        r'<' : [('R', 56)],
        r'==' : [('R', 56)],
        r'\+' : [('R', 56)],
        r'/' : [('R', 56)],
        r'-' : [('R', 56)]
    },
    25 : {
        r'>' : [('R', 15), ('R', 40)],
        EOI : [('R', 15), ('R', 40)],
        r'!=' : [('R', 15), ('R', 40)],
        r'<=' : [('R', 15), ('R', 40)],
        r'\)' : [('R', 15), ('R', 40)],
        r'>=' : [('R', 15), ('R', 40)],
        r'\n+' : [('R', 15), ('R', 40)],
        r'\*' : [('R', 15), ('R', 40)],
        r'<' : [('R', 15), ('R', 40)],
        r'==' : [('R', 15), ('R', 40)],
        r'\+' : [('R', 15), ('R', 40)],
        r'/' : [('R', 15), ('R', 40)],
        r'-' : [('R', 15), ('R', 40)]
    },
    26 : {
        r'>' : [('R', 20), ('R', 18)],
        EOI : [('R', 20), ('R', 18)],
        r'!=' : [('R', 20), ('R', 18)],
        r'<=' : [('R', 20), ('R', 18)],
        r'\)' : [('R', 20), ('R', 18)],
        r'>=' : [('R', 20), ('R', 18)],
        r'\n+' : [('R', 20), ('R', 18)],
        r'\*' : [('R', 20), ('R', 18)],
        r'<' : [('R', 20), ('R', 18)],
        r'==' : [('R', 20), ('R', 18)],
        r'\+' : [('R', 20), ('R', 18)],
        r'/' : [('R', 20), ('R', 18)],
        r'-' : [('R', 20), ('R', 18)]
    },
    27 : {
        r'>' : [('R', 17), ('R', 19)],
        EOI : [('R', 17), ('R', 19)],
        r'!=' : [('R', 17), ('R', 19)],
        r'<=' : [('R', 17), ('R', 19)],
        r'\)' : [('R', 17), ('R', 19)],
        r'>=' : [('R', 17), ('R', 19)],
        r'\n+' : [('R', 17), ('R', 19)],
        r'\*' : [('R', 17), ('R', 19)],
        r'<' : [('R', 17), ('R', 19)],
        r'==' : [('R', 17), ('R', 19)],
        r'\+' : [('R', 17), ('R', 19)],
        r'/' : [('R', 17), ('R', 19)],
        r'-' : [('R', 17), ('R', 19)]
    },
    28 : {
        r'>' : [('R', 14)],
        EOI : [('R', 14)],
        r'!=' : [('R', 14)],
        r'<=' : [('R', 14)],
        r'\)' : [('R', 14)],
        r'>=' : [('R', 14)],
        r'\n+' : [('R', 14)],
        r'\*' : [('R', 14)],
        r'<' : [('R', 14)],
        r'==' : [('R', 14)],
        r'\+' : [('R', 14)],
        r'/' : [('R', 14)],
        r'-' : [('R', 14)]
    },
    29 : {
        r'>' : [('R', 16)],
        EOI : [('R', 16)],
        r'!=' : [('R', 16)],
        r'<=' : [('R', 16)],
        r'\)' : [('R', 16)],
        r'>=' : [('R', 16)],
        r'\n+' : [('R', 16)],
        r'\*' : [('R', 16)],
        r'<' : [('R', 16)],
        r'==' : [('R', 16)],
        r'\+' : [('R', 16)],
        r'/' : [('R', 16)],
        r'-' : [('R', 16)]
    },
    30 : {
        r'>' : [('R', 36)],
        EOI : [('R', 36)],
        r'!=' : [('R', 36)],
        r'<=' : [('R', 36)],
        r'\)' : [('R', 36)],
        r'>=' : [('R', 36)],
        r'\n+' : [('R', 36)],
        r'\*' : [('R', 36)],
        r'<' : [('R', 36)],
        r'==' : [('R', 36)],
        r'\+' : [('R', 36)],
        r'/' : [('R', 36)],
        r'be' : [('R', 36)],
        r'-' : [('R', 36)]
    },
    31 : {
        r'>' : [('R', 13)],
        EOI : [('R', 13)],
        r'!=' : [('R', 13)],
        r'<=' : [('R', 13)],
        r'\)' : [('R', 13)],
        r'>=' : [('R', 13)],
        r'\n+' : [('R', 13)],
        r'\*' : [('R', 13)],
        r'<' : [('R', 13)],
        r'==' : [('R', 13)],
        r'\+' : [('R', 13)],
        r'/' : [('R', 13)],
        r'-' : [('R', 13)]
    },
    32 : {
        r'>' : [('R', 37)],
        EOI : [('R', 37)],
        r'!=' : [('R', 37)],
        r'<=' : [('R', 37)],
        r'\)' : [('R', 37)],
        r'>=' : [('R', 37)],
        r'\n+' : [('R', 37)],
        r'\*' : [('R', 37)],
        r'<' : [('R', 37)],
        r'==' : [('R', 37)],
        r'\+' : [('R', 37)],
        r'/' : [('R', 37)],
        r'-' : [('R', 37)]
    },
    33 : {
        r'>' : [('R', 12)],
        EOI : [('R', 12)],
        r'!=' : [('R', 12)],
        r'<=' : [('R', 12)],
        r'\)' : [('R', 12)],
        r'>=' : [('R', 12)],
        r'\n+' : [('R', 12)],
        r'\*' : [('R', 12)],
        r'<' : [('R', 12)],
        r'==' : [('R', 12)],
        r'\+' : [('R', 12)],
        r'/' : [('R', 12)],
        r'-' : [('R', 12)]
    },
    34 : {
        r'>' : [('R', 39)],
        EOI : [('R', 39)],
        r'!=' : [('R', 39)],
        r'<=' : [('R', 39)],
        r'\)' : [('R', 39)],
        r'>=' : [('R', 39)],
        r'\n+' : [('R', 39)],
        r'\*' : [('R', 39)],
        r'<' : [('R', 39)],
        r'==' : [('R', 39)],
        r'\+' : [('R', 39)],
        r'/' : [('R', 39)],
        r'-' : [('R', 39)]
    },
    35 : {
        r'>' : [('R', 43)],
        EOI : [('R', 43)],
        r'!=' : [('R', 43)],
        r'<=' : [('R', 43)],
        r'\)' : [('R', 43)],
        r'>=' : [('R', 43)],
        r'\n+' : [('R', 43)],
        r'\*' : [('R', 43)],
        r'<' : [('R', 43)],
        r'==' : [('R', 43)],
        r'\+' : [('R', 43)],
        r'/' : [('R', 43)],
        r'-' : [('R', 43)]
    },
    36 : {
        r'>' : [('R', 38)],
        EOI : [('R', 38)],
        r'!=' : [('R', 38)],
        r'<=' : [('R', 38)],
        r'\)' : [('R', 38)],
        r'>=' : [('R', 38)],
        r'\n+' : [('R', 38)],
        r'\*' : [('R', 38)],
        r'<' : [('R', 38)],
        r'==' : [('R', 38)],
        r'\+' : [('R', 38)],
        r'/' : [('R', 38)],
        r'-' : [('R', 38)]
    },
    37 : {
        r'>' : [('R', 42)],
        EOI : [('R', 42)],
        r'!=' : [('R', 42)],
        r'<=' : [('R', 42)],
        r'\)' : [('R', 42)],
        r'>=' : [('R', 42)],
        r'\n+' : [('R', 42)],
        r'\*' : [('R', 42)],
        r'<' : [('R', 42)],
        r'==' : [('R', 42)],
        r'\+' : [('R', 42)],
        r'/' : [('R', 42)],
        r'-' : [('R', 42)]
    },
    38 : {
        r'>' : [('R', 41)],
        EOI : [('R', 41)],
        r'!=' : [('R', 41)],
        r'<=' : [('R', 41)],
        r'\)' : [('R', 41)],
        r'>=' : [('R', 41)],
        r'\n+' : [('R', 41)],
        r'\*' : [('R', 41)],
        r'<' : [('R', 41)],
        r'==' : [('R', 41)],
        r'\+' : [('R', 41)],
        r'/' : [('R', 41)],
        r'-' : [('R', 41)]
    },
    39 : {
        MATHEXPR : [('G', 40)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    40 : {
        r'>' : [('S', 10)],
        r'!=' : [('S', 12)],
        r'==' : [('S', 14)],
        r'<=' : [('S', 16)],
        r'<' : [('S', 18)],
        r'\+' : [('S', 20)],
        r'-' : [('S', 41)],
        r'>=' : [('S', 48)],
        r'\)' : [('S', 60)]
    },
    41 : {
        TERM : [('G', 42)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)]
    },
    42 : {
        r'>' : [('R', 49)],
        EOI : [('R', 49)],
        r'!=' : [('R', 49)],
        r'\)' : [('R', 49)],
        r'<=' : [('R', 49)],
        r'>=' : [('R', 49)],
        r'\n+' : [('R', 49)],
        r'<' : [('R', 49)],
        r'==' : [('R', 49)],
        r'\+' : [('R', 49)],
        r'-' : [('R', 49)],
        r'\*' : [('S', 22)],
        r'/' : [('S', 43)]
    },
    43 : {
        FACTOR : [('G', 44)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)]
    },
    44 : {
        r'>' : [('R', 54)],
        EOI : [('R', 54)],
        r'!=' : [('R', 54)],
        r'\)' : [('R', 54)],
        r'<=' : [('R', 54)],
        r'>=' : [('R', 54)],
        r'\n+' : [('R', 54)],
        r'\*' : [('R', 54)],
        r'<' : [('R', 54)],
        r'==' : [('R', 54)],
        r'\+' : [('R', 54)],
        r'/' : [('R', 54)],
        r'-' : [('R', 54)]
    },
    45 : {
        r'>' : [('R', 52)],
        EOI : [('R', 52)],
        r'!=' : [('R', 52)],
        r'\)' : [('R', 52)],
        r'<=' : [('R', 52)],
        r'>=' : [('R', 52)],
        r'\n+' : [('R', 52)],
        r'\*' : [('R', 52)],
        r'<' : [('R', 52)],
        r'==' : [('R', 52)],
        r'\+' : [('R', 52)],
        r'/' : [('R', 52)],
        r'-' : [('R', 52)]
    },
    46 : {
        r'>' : [('R', 51)],
        EOI : [('R', 51)],
        r'!=' : [('R', 51)],
        r'\)' : [('R', 51)],
        r'<=' : [('R', 51)],
        r'>=' : [('R', 51)],
        r'\n+' : [('R', 51)],
        r'\*' : [('R', 51)],
        r'<' : [('R', 51)],
        r'==' : [('R', 51)],
        r'\+' : [('R', 51)],
        r'/' : [('R', 51)],
        r'-' : [('R', 51)]
    },
    47 : {
        r'>' : [('R', 50)],
        EOI : [('R', 50)],
        r'!=' : [('R', 50)],
        r'<=' : [('R', 50)],
        r'\)' : [('R', 50)],
        r'>=' : [('R', 50)],
        r'\n+' : [('R', 50)],
        r'\*' : [('R', 50)],
        r'<' : [('R', 50)],
        r'==' : [('R', 50)],
        r'\+' : [('R', 50)],
        r'/' : [('R', 50)],
        r'-' : [('R', 50)]
    },
    48 : {
        MATHEXPR : [('G', 49)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    49 : {
        r'>' : [('S', 10), ('R', 66)],
        EOI : [('R', 66)],
        r'!=' : [('S', 12), ('R', 66)],
        r'<=' : [('S', 16), ('R', 66)],
        r'\)' : [('R', 66)],
        r'>=' : [('S', 48), ('R', 66)],
        r'\n+' : [('R', 66)],
        r',' : [('R', 66)],
        r'<' : [('S', 18), ('R', 66)],
        r'\+' : [('S', 20), ('R', 66)],
        r'==' : [('S', 14), ('R', 66)],
        r'-' : [('S', 41), ('R', 66)]
    },
    50 : {
        r'>' : [('R', 47)],
        EOI : [('R', 47)],
        r'!=' : [('R', 47)],
        r'<=' : [('R', 47)],
        r'\)' : [('R', 47)],
        r'>=' : [('R', 47)],
        r'\n+' : [('R', 47)],
        r',' : [('R', 47)],
        r'<' : [('R', 47)],
        r'\+' : [('R', 47)],
        r'==' : [('R', 47)],
        r'-' : [('R', 47)]
    },
    51 : {
        r'>' : [('R', 62)],
        EOI : [('R', 62)],
        r'!=' : [('R', 62)],
        r'<=' : [('R', 62)],
        r'\)' : [('R', 62)],
        r'>=' : [('R', 62)],
        r'\n+' : [('R', 62)],
        r',' : [('R', 62)],
        r'<' : [('R', 62)],
        r'\+' : [('R', 62)],
        r'==' : [('R', 62)],
        r'-' : [('R', 62)]
    },
    52 : {
        r'>' : [('R', 46)],
        EOI : [('R', 46)],
        r'!=' : [('R', 46)],
        r'\)' : [('R', 46)],
        r'<=' : [('R', 46)],
        r'>=' : [('R', 46)],
        r'\n+' : [('R', 46)],
        r',' : [('R', 46)],
        r'<' : [('R', 46)],
        r'==' : [('R', 46)],
        r'\+' : [('R', 46)],
        r'-' : [('R', 46)],
        r'\*' : [('S', 22)],
        r'/' : [('S', 43)]
    },
    53 : {
        r'>' : [('R', 45)],
        EOI : [('R', 45)],
        r'!=' : [('R', 45)],
        r'\)' : [('R', 45)],
        r'<=' : [('R', 45)],
        r'>=' : [('R', 45)],
        r'\n+' : [('R', 45)],
        r',' : [('R', 45)],
        r'<' : [('R', 45)],
        r'==' : [('R', 45)],
        r'\+' : [('R', 45)],
        r'-' : [('R', 45)]
    },
    54 : {
        r'>' : [('R', 44)],
        EOI : [('R', 44)],
        r'!=' : [('R', 44)],
        r'<=' : [('R', 44)],
        r'\)' : [('R', 44)],
        r'>=' : [('R', 44)],
        r'\n+' : [('R', 44)],
        r',' : [('R', 44)],
        r'<' : [('R', 44)],
        r'==' : [('R', 44)],
        r'\+' : [('R', 44)],
        r'-' : [('R', 44)]
    },
    55 : {
        r'>' : [('R', 61)],
        EOI : [('R', 61)],
        r'!=' : [('R', 61)],
        r'<=' : [('R', 61)],
        r'\)' : [('R', 61)],
        r'>=' : [('R', 61)],
        r'\n+' : [('R', 61)],
        r',' : [('R', 61)],
        r'<' : [('R', 61)],
        r'\+' : [('R', 61)],
        r'==' : [('R', 61)],
        r'-' : [('R', 61)]
    },
    56 : {
        r'>' : [('R', 60)],
        EOI : [('R', 60)],
        r'!=' : [('R', 60)],
        r'\)' : [('R', 60)],
        r'<=' : [('R', 60)],
        r'>=' : [('R', 60)],
        r'\n+' : [('R', 60)],
        r',' : [('R', 60)],
        r'<' : [('R', 60)],
        r'==' : [('R', 60)],
        r'\+' : [('R', 60)],
        r'-' : [('R', 60)]
    },
    57 : {
        r'>' : [('R', 59)],
        EOI : [('R', 59)],
        r'!=' : [('R', 59)],
        r'\)' : [('R', 59)],
        r'<=' : [('R', 59)],
        r'>=' : [('R', 59)],
        r'\n+' : [('R', 59)],
        r',' : [('R', 59)],
        r'<' : [('R', 59)],
        r'==' : [('R', 59)],
        r'\+' : [('R', 59)],
        r'-' : [('R', 59)]
    },
    58 : {
        r'>' : [('R', 58)],
        EOI : [('R', 58)],
        r'!=' : [('R', 58)],
        r'\)' : [('R', 58)],
        r'<=' : [('R', 58)],
        r'>=' : [('R', 58)],
        r'\n+' : [('R', 58)],
        r',' : [('R', 58)],
        r'<' : [('R', 58)],
        r'==' : [('R', 58)],
        r'\+' : [('R', 58)],
        r'-' : [('R', 58)]
    },
    59 : {
        r'>' : [('R', 57)],
        EOI : [('R', 57)],
        r'!=' : [('R', 57)],
        r'\)' : [('R', 57)],
        r'<=' : [('R', 57)],
        r'>=' : [('R', 57)],
        r'\n+' : [('R', 57)],
        r',' : [('R', 57)],
        r'<' : [('R', 57)],
        r'==' : [('R', 57)],
        r'\+' : [('R', 57)],
        r'-' : [('R', 57)]
    },
    60 : {
        r'>' : [('R', 55)],
        EOI : [('R', 55)],
        r'!=' : [('R', 55)],
        r'<=' : [('R', 55)],
        r'\)' : [('R', 55)],
        r'>=' : [('R', 55)],
        r'\n+' : [('R', 55)],
        r'\*' : [('R', 55)],
        r'<' : [('R', 55)],
        r'==' : [('R', 55)],
        r'\+' : [('R', 55)],
        r'/' : [('R', 55)],
        r'-' : [('R', 55)]
    },
    61 : {
        r'\n+' : [('R', 9)],
        EOI : [('R', 9)],
        r'//DEDENTATION-MARKER//' : [('R', 9)]
    },
    62 : {
        r'\n+' : [('R', 35)],
        EOI : [('R', 35)],
        r'//DEDENTATION-MARKER//' : [('R', 35)],
        EXPRESSION : [('G', 63)],
        MATHEXPR : [('G', 9)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    63 : {
        r'\n+' : [('R', 34)],
        EOI : [('R', 34)],
        r'//DEDENTATION-MARKER//' : [('R', 34)]
    },
    64 : {
        r'\n+' : [('R', 8)],
        EOI : [('R', 8)],
        r'//DEDENTATION-MARKER//' : [('R', 8)]
    },
    65 : {
        ID : [('G', 66)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)]
    },
    66 : {
        r'be' : [('S', 67)]
    },
    67 : {
        EXPRESSION : [('G', 68)],
        MATHEXPR : [('G', 9)],
        COMPARISON : [('G', 84), ('G', 50)],
        GEQ : [('G', 51)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    68 : {
        r'\n+' : [('R', 21)],
        EOI : [('R', 21)],
        r'//DEDENTATION-MARKER//' : [('R', 21)]
    },
    69 : {
        r'\n+' : [('R', 7)],
        EOI : [('R', 7)],
        r'//DEDENTATION-MARKER//' : [('R', 7)]
    },
    70 : {
        r'instruction' : [('S', 71)]
    },
    71 : {
        MARK : [('G', 72)],
        NUMBER : [('G', 73)],
        BOOL : [('G', 25), ('G', 74)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        ID : [('G', 75)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)]
    },
    72 : {
        r'\n+' : [('R', 30)],
        EOI : [('R', 30)],
        r'//DEDENTATION-MARKER//' : [('R', 30)]
    },
    73 : {
        r'\n+' : [('R', 33)],
        EOI : [('R', 33)]
    },
    74 : {
        r'\n+' : [('R', 40)],
        EOI : [('R', 40)]
    },
    75 : {
        r'\n+' : [('R', 32)],
        EOI : [('R', 32)]
    },
    76 : {
        r'\n+' : [('R', 6)],
        EOI : [('R', 6)],
        r'//DEDENTATION-MARKER//' : [('R', 6)]
    },
    77 : {
        MARK : [('G', 78)],
        NUMBER : [('G', 73)],
        BOOL : [('G', 25), ('G', 74)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        ID : [('G', 75)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)]
    },
    78 : {
        r'\n+' : [('S', 79)]
    },
    79 : {
        STATEMENT_LIST : [('G', 80)],
        STATEMENT : [('G', 3)],
        RETURN : [('G', 6)],
        r'return' : [('S', 7)],
        PRINT : [('G', 61)],
        r'print' : [('S', 62)],
        ASSIGNMENT : [('G', 64)],
        r'let' : [('S', 65)],
        GOTO : [('G', 69)],
        r'goto' : [('S', 70)],
        MARKER : [('G', 76)],
        r'@' : [('S', 77)],
        CONDITIONAL : [('G', 81)],
        IF_THEN_ELSE : [('G', 82)],
        r'if' : [('S', 83)],
        IF_THEN : [('G', 96)]
    },
    80 : {
        r'\n+' : [('R', 31)],
        EOI : [('R', 31)],
        r'//DEDENTATION-MARKER//' : [('R', 31)]
    },
    81 : {
        r'\n+' : [('R', 5)],
        EOI : [('R', 5)],
        r'//DEDENTATION-MARKER//' : [('R', 5)]
    },
    82 : {
        r'\n+' : [('R', 23)],
        EOI : [('R', 23)],
        r'//DEDENTATION-MARKER//' : [('R', 23)]
    },
    83 : {
        COMPARISON : [('G', 84)],
        GEQ : [('G', 51)],
        MATHEXPR : [('G', 15), ('G', 11), ('G', 40), ('G', 98), ('G', 49), ('G', 17), ('G', 13), ('G', 19), ('G', 9)],
        TERM : [('G', 52)],
        FACTOR : [('G', 45)],
        VALUE : [('G', 24)],
        BOOL : [('G', 25)],
        r'False' : [('S', 26)],
        r'True' : [('S', 27)],
        LABEL : [('G', 28)],
        ID : [('G', 29)],
        r'[_a-zA-Z][_a-zA-Z0-9]*' : [('S', 30)],
        STRING : [('G', 31)],
        r'"[^"\n]*"' : [('S', 32)],
        NUMBER : [('G', 33)],
        FLOAT : [('G', 34)],
        r'\d*\.\d+' : [('S', 35)],
        INT : [('G', 36)],
        r'[1-9]\d*' : [('S', 37)],
        r'0' : [('S', 38)],
        r'\(' : [('S', 39)],
        DIVIDE : [('G', 46)],
        MULTIPLY : [('G', 47)],
        SUBTRACT : [('G', 53)],
        ADD : [('G', 54)],
        LE : [('G', 55)],
        LEQ : [('G', 56)],
        EQ : [('G', 57)],
        NEQ : [('G', 58)],
        GE : [('G', 59)]
    },
    84 : {
        r'>' : [('R', 47)],
        r'!=' : [('R', 47)],
        r'<=' : [('R', 47)],
        r'>=' : [('R', 47)],
        r'<' : [('R', 47)],
        r'==' : [('R', 47)],
        r'\+' : [('R', 47)],
        r'-' : [('R', 47)],
        r',' : [('S', 85)]
    },
    85 : {
        r'then' : [('S', 86)]
    },
    86 : {
        BLOCK : [('G', 87)],
        r'\n+' : [('S', 91)]
    },
    87 : {
        r'\n+' : [('S', 88), ('R', 24)],
        EOI : [('R', 24)],
        r'//DEDENTATION-MARKER//' : [('R', 24)]
    },
    88 : {
        r'else' : [('S', 89)]
    },
    89 : {
        BLOCK : [('G', 90)],
        r'\n+' : [('S', 91)]
    },
    90 : {
        r'\n+' : [('R', 25)],
        EOI : [('R', 25)],
        r'//DEDENTATION-MARKER//' : [('R', 25)]
    },
    91 : {
        INDENT : [('G', 92)],
        r'//INDENTATION-MARKER//' : [('S', 97)]
    },
    92 : {
        STATEMENT_LIST : [('G', 93)],
        STATEMENT : [('G', 3)],
        RETURN : [('G', 6)],
        r'return' : [('S', 7)],
        PRINT : [('G', 61)],
        r'print' : [('S', 62)],
        ASSIGNMENT : [('G', 64)],
        r'let' : [('S', 65)],
        GOTO : [('G', 69)],
        r'goto' : [('S', 70)],
        MARKER : [('G', 76)],
        r'@' : [('S', 77)],
        CONDITIONAL : [('G', 81)],
        IF_THEN_ELSE : [('G', 82)],
        r'if' : [('S', 83)],
        IF_THEN : [('G', 96)]
    },
    93 : {
        DEDENT : [('G', 94)],
        r'//DEDENTATION-MARKER//' : [('S', 95)]
    },
    94 : {
        r'\n+' : [('R', 28)],
        EOI : [('R', 28)]
    },
    95 : {
        r'\n+' : [('R', 27)],
        EOI : [('R', 27)]
    },
    96 : {
        r'\n+' : [('R', 22)],
        EOI : [('R', 22)],
        r'//DEDENTATION-MARKER//' : [('R', 22)]
    },
    97 : {
        r'goto' : [('R', 26)],
        r'print' : [('R', 26)],
        r'return' : [('R', 26)],
        r'@' : [('R', 26)],
        r'let' : [('R', 26)],
        r'if' : [('R', 26)]
    },
    98 : {
        r'>' : [('S', 10)],
        r'!=' : [('S', 12)],
        r'==' : [('S', 14)],
        r'<=' : [('S', 16)],
        r'<' : [('S', 18)],
        r'\+' : [('S', 20)],
        r'-' : [('S', 41)],
        r'>=' : [('S', 48)]
    },
    99 : {
        EOI : [('R', 1)]
    }
}